/* 
 * NASCAR Data API
 *
 * Current & Preview API behavior.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Container for ingesting cone coordinate data for a specific race
    /// </summary>
    [DataContract]
        public partial class ConeCoordinatesIngest :  IEquatable<ConeCoordinatesIngest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConeCoordinatesIngest" /> class.
        /// </summary>
        /// <param name="raceId">Associated race identifier.</param>
        /// <param name="source">source.</param>
        /// <param name="coordinates">Array of coordinate data representing safety cone placements.</param>
        public ConeCoordinatesIngest(int? raceId = default(int?), string source = default(string), Collection<Coordinate> coordinates = default(Collection<Coordinate>))
        {
            this.RaceId = raceId;
            this.Source = source;
            this.Coordinates = coordinates;
        }
        
        /// <summary>
        /// Associated race identifier
        /// </summary>
        /// <value>Associated race identifier</value>
        [DataMember(Name="RaceId", EmitDefaultValue=false)]
        public int? RaceId { get; set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name="source", EmitDefaultValue=false)]
        public string Source { get; set; }

        /// <summary>
        /// Array of coordinate data representing safety cone placements
        /// </summary>
        /// <value>Array of coordinate data representing safety cone placements</value>
        [DataMember(Name="coordinates", EmitDefaultValue=false)]
        public Collection<Coordinate> Coordinates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConeCoordinatesIngest {\n");
            sb.Append("  RaceId: ").Append(RaceId).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Coordinates: ").Append(Coordinates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConeCoordinatesIngest);
        }

        /// <summary>
        /// Returns true if ConeCoordinatesIngest instances are equal
        /// </summary>
        /// <param name="input">Instance of ConeCoordinatesIngest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConeCoordinatesIngest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RaceId == input.RaceId ||
                    (this.RaceId != null &&
                    this.RaceId.Equals(input.RaceId))
                ) && 
                (
                    this.Source == input.Source ||
                    (this.Source != null &&
                    this.Source.Equals(input.Source))
                ) && 
                (
                    this.Coordinates == input.Coordinates ||
                    this.Coordinates != null &&
                    input.Coordinates != null &&
                    this.Coordinates.SequenceEqual(input.Coordinates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RaceId != null)
                    hashCode = hashCode * 59 + this.RaceId.GetHashCode();
                if (this.Source != null)
                    hashCode = hashCode * 59 + this.Source.GetHashCode();
                if (this.Coordinates != null)
                    hashCode = hashCode * 59 + this.Coordinates.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
