/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// DriverPointsView
    /// </summary>
    [DataContract]
        public partial class DriverPointsView :  IEquatable<DriverPointsView>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DriverPointsView" /> class.
        /// </summary>
        /// <param name="seriesId">seriesId.</param>
        /// <param name="historyRaceId">historyRaceId.</param>
        /// <param name="timingRunId">timingRunId.</param>
        /// <param name="playoffRoundNumber">playoffRoundNumber.</param>
        /// <param name="driverPoints">driverPoints.</param>
        public DriverPointsView(int? seriesId = default(int?), int? historyRaceId = default(int?), int? timingRunId = default(int?), int? playoffRoundNumber = default(int?), Collection<LiveDriverPointsSlim> driverPoints = default(Collection<LiveDriverPointsSlim>))
        {
            this.SeriesId = seriesId;
            this.HistoryRaceId = historyRaceId;
            this.TimingRunId = timingRunId;
            this.PlayoffRoundNumber = playoffRoundNumber;
            this.DriverPoints = driverPoints;
        }
        
        /// <summary>
        /// Gets or Sets SeriesId
        /// </summary>
        [DataMember(Name="series_id", EmitDefaultValue=false)]
        public int? SeriesId { get; set; }

        /// <summary>
        /// Gets or Sets HistoryRaceId
        /// </summary>
        [DataMember(Name="history_race_id", EmitDefaultValue=false)]
        public int? HistoryRaceId { get; set; }

        /// <summary>
        /// Gets or Sets TimingRunId
        /// </summary>
        [DataMember(Name="timing_run_id", EmitDefaultValue=false)]
        public int? TimingRunId { get; set; }

        /// <summary>
        /// Gets or Sets PlayoffRoundNumber
        /// </summary>
        [DataMember(Name="playoff_round_number", EmitDefaultValue=false)]
        public int? PlayoffRoundNumber { get; set; }

        /// <summary>
        /// Gets or Sets DriverPoints
        /// </summary>
        [DataMember(Name="DriverPoints", EmitDefaultValue=false)]
        public Collection<LiveDriverPointsSlim> DriverPoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DriverPointsView {\n");
            sb.Append("  SeriesId: ").Append(SeriesId).Append("\n");
            sb.Append("  HistoryRaceId: ").Append(HistoryRaceId).Append("\n");
            sb.Append("  TimingRunId: ").Append(TimingRunId).Append("\n");
            sb.Append("  PlayoffRoundNumber: ").Append(PlayoffRoundNumber).Append("\n");
            sb.Append("  DriverPoints: ").Append(DriverPoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DriverPointsView);
        }

        /// <summary>
        /// Returns true if DriverPointsView instances are equal
        /// </summary>
        /// <param name="input">Instance of DriverPointsView to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DriverPointsView input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SeriesId == input.SeriesId ||
                    (this.SeriesId != null &&
                    this.SeriesId.Equals(input.SeriesId))
                ) && 
                (
                    this.HistoryRaceId == input.HistoryRaceId ||
                    (this.HistoryRaceId != null &&
                    this.HistoryRaceId.Equals(input.HistoryRaceId))
                ) && 
                (
                    this.TimingRunId == input.TimingRunId ||
                    (this.TimingRunId != null &&
                    this.TimingRunId.Equals(input.TimingRunId))
                ) && 
                (
                    this.PlayoffRoundNumber == input.PlayoffRoundNumber ||
                    (this.PlayoffRoundNumber != null &&
                    this.PlayoffRoundNumber.Equals(input.PlayoffRoundNumber))
                ) && 
                (
                    this.DriverPoints == input.DriverPoints ||
                    this.DriverPoints != null &&
                    input.DriverPoints != null &&
                    this.DriverPoints.SequenceEqual(input.DriverPoints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SeriesId != null)
                    hashCode = hashCode * 59 + this.SeriesId.GetHashCode();
                if (this.HistoryRaceId != null)
                    hashCode = hashCode * 59 + this.HistoryRaceId.GetHashCode();
                if (this.TimingRunId != null)
                    hashCode = hashCode * 59 + this.TimingRunId.GetHashCode();
                if (this.PlayoffRoundNumber != null)
                    hashCode = hashCode * 59 + this.PlayoffRoundNumber.GetHashCode();
                if (this.DriverPoints != null)
                    hashCode = hashCode * 59 + this.DriverPoints.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
