/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// EditorSeries
    /// </summary>
    [DataContract]
        public partial class EditorSeries :  IEquatable<EditorSeries>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets PublishState
        /// </summary>
        [DataMember(Name="PublishState", EmitDefaultValue=false)]
        public PublishState? PublishState { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EditorSeries" /> class.
        /// </summary>
        /// <param name="publishState">publishState.</param>
        /// <param name="id">id.</param>
        /// <param name="trackingId">trackingId.</param>
        /// <param name="inDataWarehouse">inDataWarehouse.</param>
        /// <param name="manuallySet">manuallySet.</param>
        /// <param name="lastUpdate">lastUpdate.</param>
        /// <param name="lastUpdatedBy">lastUpdatedBy.</param>
        /// <param name="name">name.</param>
        /// <param name="shortName">shortName.</param>
        /// <param name="abbreviation">abbreviation.</param>
        /// <param name="logo">logo.</param>
        public EditorSeries(PublishState? publishState = default(PublishState?), int? id = default(int?), Guid? trackingId = default(Guid?), bool? inDataWarehouse = default(bool?), bool? manuallySet = default(bool?), DateTimeOffset? lastUpdate = default(DateTimeOffset?), string lastUpdatedBy = default(string), string name = default(string), string shortName = default(string), string abbreviation = default(string), string logo = default(string))
        {
            this.PublishState = publishState;
            this.Id = id;
            this.TrackingId = trackingId;
            this.InDataWarehouse = inDataWarehouse;
            this.ManuallySet = manuallySet;
            this.LastUpdate = lastUpdate;
            this.LastUpdatedBy = lastUpdatedBy;
            this.Name = name;
            this.ShortName = shortName;
            this.Abbreviation = abbreviation;
            this.Logo = logo;
        }
        

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets TrackingId
        /// </summary>
        [DataMember(Name="tracking_id", EmitDefaultValue=false)]
        public Guid? TrackingId { get; set; }

        /// <summary>
        /// Gets or Sets InDataWarehouse
        /// </summary>
        [DataMember(Name="InDataWarehouse", EmitDefaultValue=false)]
        public bool? InDataWarehouse { get; set; }

        /// <summary>
        /// Gets or Sets ManuallySet
        /// </summary>
        [DataMember(Name="Manually_Set", EmitDefaultValue=false)]
        public bool? ManuallySet { get; set; }

        /// <summary>
        /// Gets or Sets LastUpdate
        /// </summary>
        [DataMember(Name="LastUpdate", EmitDefaultValue=false)]
        public DateTimeOffset? LastUpdate { get; set; }

        /// <summary>
        /// Gets or Sets LastUpdatedBy
        /// </summary>
        [DataMember(Name="LastUpdatedBy", EmitDefaultValue=false)]
        public string LastUpdatedBy { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ShortName
        /// </summary>
        [DataMember(Name="ShortName", EmitDefaultValue=false)]
        public string ShortName { get; set; }

        /// <summary>
        /// Gets or Sets Abbreviation
        /// </summary>
        [DataMember(Name="Abbreviation", EmitDefaultValue=false)]
        public string Abbreviation { get; set; }

        /// <summary>
        /// Gets or Sets Logo
        /// </summary>
        [DataMember(Name="Logo", EmitDefaultValue=false)]
        public string Logo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EditorSeries {\n");
            sb.Append("  PublishState: ").Append(PublishState).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TrackingId: ").Append(TrackingId).Append("\n");
            sb.Append("  InDataWarehouse: ").Append(InDataWarehouse).Append("\n");
            sb.Append("  ManuallySet: ").Append(ManuallySet).Append("\n");
            sb.Append("  LastUpdate: ").Append(LastUpdate).Append("\n");
            sb.Append("  LastUpdatedBy: ").Append(LastUpdatedBy).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ShortName: ").Append(ShortName).Append("\n");
            sb.Append("  Abbreviation: ").Append(Abbreviation).Append("\n");
            sb.Append("  Logo: ").Append(Logo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EditorSeries);
        }

        /// <summary>
        /// Returns true if EditorSeries instances are equal
        /// </summary>
        /// <param name="input">Instance of EditorSeries to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EditorSeries input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PublishState == input.PublishState ||
                    (this.PublishState != null &&
                    this.PublishState.Equals(input.PublishState))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.TrackingId == input.TrackingId ||
                    (this.TrackingId != null &&
                    this.TrackingId.Equals(input.TrackingId))
                ) && 
                (
                    this.InDataWarehouse == input.InDataWarehouse ||
                    (this.InDataWarehouse != null &&
                    this.InDataWarehouse.Equals(input.InDataWarehouse))
                ) && 
                (
                    this.ManuallySet == input.ManuallySet ||
                    (this.ManuallySet != null &&
                    this.ManuallySet.Equals(input.ManuallySet))
                ) && 
                (
                    this.LastUpdate == input.LastUpdate ||
                    (this.LastUpdate != null &&
                    this.LastUpdate.Equals(input.LastUpdate))
                ) && 
                (
                    this.LastUpdatedBy == input.LastUpdatedBy ||
                    (this.LastUpdatedBy != null &&
                    this.LastUpdatedBy.Equals(input.LastUpdatedBy))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ShortName == input.ShortName ||
                    (this.ShortName != null &&
                    this.ShortName.Equals(input.ShortName))
                ) && 
                (
                    this.Abbreviation == input.Abbreviation ||
                    (this.Abbreviation != null &&
                    this.Abbreviation.Equals(input.Abbreviation))
                ) && 
                (
                    this.Logo == input.Logo ||
                    (this.Logo != null &&
                    this.Logo.Equals(input.Logo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PublishState != null)
                    hashCode = hashCode * 59 + this.PublishState.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.TrackingId != null)
                    hashCode = hashCode * 59 + this.TrackingId.GetHashCode();
                if (this.InDataWarehouse != null)
                    hashCode = hashCode * 59 + this.InDataWarehouse.GetHashCode();
                if (this.ManuallySet != null)
                    hashCode = hashCode * 59 + this.ManuallySet.GetHashCode();
                if (this.LastUpdate != null)
                    hashCode = hashCode * 59 + this.LastUpdate.GetHashCode();
                if (this.LastUpdatedBy != null)
                    hashCode = hashCode * 59 + this.LastUpdatedBy.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ShortName != null)
                    hashCode = hashCode * 59 + this.ShortName.GetHashCode();
                if (this.Abbreviation != null)
                    hashCode = hashCode * 59 + this.Abbreviation.GetHashCode();
                if (this.Logo != null)
                    hashCode = hashCode * 59 + this.Logo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
