/* 
 * NASCAR Data API
 *
 * Current & Preview API behavior.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Represents the fastest lap award details for a race
    /// </summary>
    [DataContract]
        public partial class FastestLapAwards :  IEquatable<FastestLapAwards>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FastestLapAwards" /> class.
        /// </summary>
        /// <param name="lapTime">The fastest lap time recorded.</param>
        /// <param name="carNumber">The car number that recorded the fastest lap.</param>
        /// <param name="lap">The lap number on which the fastest time was recorded.</param>
        public FastestLapAwards(int? lapTime = default(int?), string carNumber = default(string), int? lap = default(int?))
        {
            this.LapTime = lapTime;
            this.CarNumber = carNumber;
            this.Lap = lap;
        }
        
        /// <summary>
        /// The fastest lap time recorded
        /// </summary>
        /// <value>The fastest lap time recorded</value>
        [DataMember(Name="lap_time", EmitDefaultValue=false)]
        public int? LapTime { get; set; }

        /// <summary>
        /// The car number that recorded the fastest lap
        /// </summary>
        /// <value>The car number that recorded the fastest lap</value>
        [DataMember(Name="car_number", EmitDefaultValue=false)]
        public string CarNumber { get; set; }

        /// <summary>
        /// The lap number on which the fastest time was recorded
        /// </summary>
        /// <value>The lap number on which the fastest time was recorded</value>
        [DataMember(Name="lap", EmitDefaultValue=false)]
        public int? Lap { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FastestLapAwards {\n");
            sb.Append("  LapTime: ").Append(LapTime).Append("\n");
            sb.Append("  CarNumber: ").Append(CarNumber).Append("\n");
            sb.Append("  Lap: ").Append(Lap).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FastestLapAwards);
        }

        /// <summary>
        /// Returns true if FastestLapAwards instances are equal
        /// </summary>
        /// <param name="input">Instance of FastestLapAwards to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FastestLapAwards input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LapTime == input.LapTime ||
                    (this.LapTime != null &&
                    this.LapTime.Equals(input.LapTime))
                ) && 
                (
                    this.CarNumber == input.CarNumber ||
                    (this.CarNumber != null &&
                    this.CarNumber.Equals(input.CarNumber))
                ) && 
                (
                    this.Lap == input.Lap ||
                    (this.Lap != null &&
                    this.Lap.Equals(input.Lap))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LapTime != null)
                    hashCode = hashCode * 59 + this.LapTime.GetHashCode();
                if (this.CarNumber != null)
                    hashCode = hashCode * 59 + this.CarNumber.GetHashCode();
                if (this.Lap != null)
                    hashCode = hashCode * 59 + this.Lap.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
