/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// InfractionMapping
    /// </summary>
    [DataContract]
        public partial class InfractionMapping :  IEquatable<InfractionMapping>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets PublishState
        /// </summary>
        [DataMember(Name="PublishState", EmitDefaultValue=false)]
        public PublishState? PublishState { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InfractionMapping" /> class.
        /// </summary>
        /// <param name="publishState">publishState.</param>
        /// <param name="id">id.</param>
        /// <param name="trackingId">trackingId.</param>
        /// <param name="inDataWarehouse">inDataWarehouse.</param>
        /// <param name="manuallySet">manuallySet.</param>
        /// <param name="lastUpdate">lastUpdate.</param>
        /// <param name="lastUpdatedBy">lastUpdatedBy.</param>
        /// <param name="nascarOneRaceId">nascarOneRaceId.</param>
        /// <param name="timingRunId">timingRunId.</param>
        /// <param name="racingInfractionId">racingInfractionId.</param>
        /// <param name="vehicle">vehicle.</param>
        /// <param name="infraction">infraction.</param>
        /// <param name="lap">lap.</param>
        /// <param name="lapAssessed">lapAssessed.</param>
        /// <param name="timeOfRace">timeOfRace.</param>
        /// <param name="flagState">flagState.</param>
        /// <param name="penalty">penalty.</param>
        /// <param name="notes">notes.</param>
        public InfractionMapping(PublishState? publishState = default(PublishState?), int? id = default(int?), Guid? trackingId = default(Guid?), bool? inDataWarehouse = default(bool?), bool? manuallySet = default(bool?), DateTimeOffset? lastUpdate = default(DateTimeOffset?), string lastUpdatedBy = default(string), int? nascarOneRaceId = default(int?), int? timingRunId = default(int?), int? racingInfractionId = default(int?), string vehicle = default(string), string infraction = default(string), int? lap = default(int?), int? lapAssessed = default(int?), DateTimeOffset? timeOfRace = default(DateTimeOffset?), string flagState = default(string), string penalty = default(string), string notes = default(string))
        {
            this.PublishState = publishState;
            this.Id = id;
            this.TrackingId = trackingId;
            this.InDataWarehouse = inDataWarehouse;
            this.ManuallySet = manuallySet;
            this.LastUpdate = lastUpdate;
            this.LastUpdatedBy = lastUpdatedBy;
            this.NascarOneRaceId = nascarOneRaceId;
            this.TimingRunId = timingRunId;
            this.RacingInfractionId = racingInfractionId;
            this.Vehicle = vehicle;
            this.Infraction = infraction;
            this.Lap = lap;
            this.LapAssessed = lapAssessed;
            this.TimeOfRace = timeOfRace;
            this.FlagState = flagState;
            this.Penalty = penalty;
            this.Notes = notes;
        }
        

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets TrackingId
        /// </summary>
        [DataMember(Name="tracking_id", EmitDefaultValue=false)]
        public Guid? TrackingId { get; set; }

        /// <summary>
        /// Gets or Sets InDataWarehouse
        /// </summary>
        [DataMember(Name="InDataWarehouse", EmitDefaultValue=false)]
        public bool? InDataWarehouse { get; set; }

        /// <summary>
        /// Gets or Sets ManuallySet
        /// </summary>
        [DataMember(Name="Manually_Set", EmitDefaultValue=false)]
        public bool? ManuallySet { get; set; }

        /// <summary>
        /// Gets or Sets LastUpdate
        /// </summary>
        [DataMember(Name="LastUpdate", EmitDefaultValue=false)]
        public DateTimeOffset? LastUpdate { get; set; }

        /// <summary>
        /// Gets or Sets LastUpdatedBy
        /// </summary>
        [DataMember(Name="LastUpdatedBy", EmitDefaultValue=false)]
        public string LastUpdatedBy { get; set; }

        /// <summary>
        /// Gets or Sets NascarOneRaceId
        /// </summary>
        [DataMember(Name="NascarOne_RaceId", EmitDefaultValue=false)]
        public int? NascarOneRaceId { get; set; }

        /// <summary>
        /// Gets or Sets TimingRunId
        /// </summary>
        [DataMember(Name="Timing_RunId", EmitDefaultValue=false)]
        public int? TimingRunId { get; set; }

        /// <summary>
        /// Gets or Sets RacingInfractionId
        /// </summary>
        [DataMember(Name="Racing_InfractionId", EmitDefaultValue=false)]
        public int? RacingInfractionId { get; set; }

        /// <summary>
        /// Gets or Sets Vehicle
        /// </summary>
        [DataMember(Name="Vehicle", EmitDefaultValue=false)]
        public string Vehicle { get; set; }

        /// <summary>
        /// Gets or Sets Infraction
        /// </summary>
        [DataMember(Name="Infraction", EmitDefaultValue=false)]
        public string Infraction { get; set; }

        /// <summary>
        /// Gets or Sets Lap
        /// </summary>
        [DataMember(Name="Lap", EmitDefaultValue=false)]
        public int? Lap { get; set; }

        /// <summary>
        /// Gets or Sets LapAssessed
        /// </summary>
        [DataMember(Name="LapAssessed", EmitDefaultValue=false)]
        public int? LapAssessed { get; set; }

        /// <summary>
        /// Gets or Sets TimeOfRace
        /// </summary>
        [DataMember(Name="Time_Of_Race", EmitDefaultValue=false)]
        public DateTimeOffset? TimeOfRace { get; set; }

        /// <summary>
        /// Gets or Sets FlagState
        /// </summary>
        [DataMember(Name="FlagState", EmitDefaultValue=false)]
        public string FlagState { get; set; }

        /// <summary>
        /// Gets or Sets Penalty
        /// </summary>
        [DataMember(Name="Penalty", EmitDefaultValue=false)]
        public string Penalty { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name="Notes", EmitDefaultValue=false)]
        public string Notes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InfractionMapping {\n");
            sb.Append("  PublishState: ").Append(PublishState).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TrackingId: ").Append(TrackingId).Append("\n");
            sb.Append("  InDataWarehouse: ").Append(InDataWarehouse).Append("\n");
            sb.Append("  ManuallySet: ").Append(ManuallySet).Append("\n");
            sb.Append("  LastUpdate: ").Append(LastUpdate).Append("\n");
            sb.Append("  LastUpdatedBy: ").Append(LastUpdatedBy).Append("\n");
            sb.Append("  NascarOneRaceId: ").Append(NascarOneRaceId).Append("\n");
            sb.Append("  TimingRunId: ").Append(TimingRunId).Append("\n");
            sb.Append("  RacingInfractionId: ").Append(RacingInfractionId).Append("\n");
            sb.Append("  Vehicle: ").Append(Vehicle).Append("\n");
            sb.Append("  Infraction: ").Append(Infraction).Append("\n");
            sb.Append("  Lap: ").Append(Lap).Append("\n");
            sb.Append("  LapAssessed: ").Append(LapAssessed).Append("\n");
            sb.Append("  TimeOfRace: ").Append(TimeOfRace).Append("\n");
            sb.Append("  FlagState: ").Append(FlagState).Append("\n");
            sb.Append("  Penalty: ").Append(Penalty).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InfractionMapping);
        }

        /// <summary>
        /// Returns true if InfractionMapping instances are equal
        /// </summary>
        /// <param name="input">Instance of InfractionMapping to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InfractionMapping input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PublishState == input.PublishState ||
                    (this.PublishState != null &&
                    this.PublishState.Equals(input.PublishState))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.TrackingId == input.TrackingId ||
                    (this.TrackingId != null &&
                    this.TrackingId.Equals(input.TrackingId))
                ) && 
                (
                    this.InDataWarehouse == input.InDataWarehouse ||
                    (this.InDataWarehouse != null &&
                    this.InDataWarehouse.Equals(input.InDataWarehouse))
                ) && 
                (
                    this.ManuallySet == input.ManuallySet ||
                    (this.ManuallySet != null &&
                    this.ManuallySet.Equals(input.ManuallySet))
                ) && 
                (
                    this.LastUpdate == input.LastUpdate ||
                    (this.LastUpdate != null &&
                    this.LastUpdate.Equals(input.LastUpdate))
                ) && 
                (
                    this.LastUpdatedBy == input.LastUpdatedBy ||
                    (this.LastUpdatedBy != null &&
                    this.LastUpdatedBy.Equals(input.LastUpdatedBy))
                ) && 
                (
                    this.NascarOneRaceId == input.NascarOneRaceId ||
                    (this.NascarOneRaceId != null &&
                    this.NascarOneRaceId.Equals(input.NascarOneRaceId))
                ) && 
                (
                    this.TimingRunId == input.TimingRunId ||
                    (this.TimingRunId != null &&
                    this.TimingRunId.Equals(input.TimingRunId))
                ) && 
                (
                    this.RacingInfractionId == input.RacingInfractionId ||
                    (this.RacingInfractionId != null &&
                    this.RacingInfractionId.Equals(input.RacingInfractionId))
                ) && 
                (
                    this.Vehicle == input.Vehicle ||
                    (this.Vehicle != null &&
                    this.Vehicle.Equals(input.Vehicle))
                ) && 
                (
                    this.Infraction == input.Infraction ||
                    (this.Infraction != null &&
                    this.Infraction.Equals(input.Infraction))
                ) && 
                (
                    this.Lap == input.Lap ||
                    (this.Lap != null &&
                    this.Lap.Equals(input.Lap))
                ) && 
                (
                    this.LapAssessed == input.LapAssessed ||
                    (this.LapAssessed != null &&
                    this.LapAssessed.Equals(input.LapAssessed))
                ) && 
                (
                    this.TimeOfRace == input.TimeOfRace ||
                    (this.TimeOfRace != null &&
                    this.TimeOfRace.Equals(input.TimeOfRace))
                ) && 
                (
                    this.FlagState == input.FlagState ||
                    (this.FlagState != null &&
                    this.FlagState.Equals(input.FlagState))
                ) && 
                (
                    this.Penalty == input.Penalty ||
                    (this.Penalty != null &&
                    this.Penalty.Equals(input.Penalty))
                ) && 
                (
                    this.Notes == input.Notes ||
                    (this.Notes != null &&
                    this.Notes.Equals(input.Notes))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PublishState != null)
                    hashCode = hashCode * 59 + this.PublishState.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.TrackingId != null)
                    hashCode = hashCode * 59 + this.TrackingId.GetHashCode();
                if (this.InDataWarehouse != null)
                    hashCode = hashCode * 59 + this.InDataWarehouse.GetHashCode();
                if (this.ManuallySet != null)
                    hashCode = hashCode * 59 + this.ManuallySet.GetHashCode();
                if (this.LastUpdate != null)
                    hashCode = hashCode * 59 + this.LastUpdate.GetHashCode();
                if (this.LastUpdatedBy != null)
                    hashCode = hashCode * 59 + this.LastUpdatedBy.GetHashCode();
                if (this.NascarOneRaceId != null)
                    hashCode = hashCode * 59 + this.NascarOneRaceId.GetHashCode();
                if (this.TimingRunId != null)
                    hashCode = hashCode * 59 + this.TimingRunId.GetHashCode();
                if (this.RacingInfractionId != null)
                    hashCode = hashCode * 59 + this.RacingInfractionId.GetHashCode();
                if (this.Vehicle != null)
                    hashCode = hashCode * 59 + this.Vehicle.GetHashCode();
                if (this.Infraction != null)
                    hashCode = hashCode * 59 + this.Infraction.GetHashCode();
                if (this.Lap != null)
                    hashCode = hashCode * 59 + this.Lap.GetHashCode();
                if (this.LapAssessed != null)
                    hashCode = hashCode * 59 + this.LapAssessed.GetHashCode();
                if (this.TimeOfRace != null)
                    hashCode = hashCode * 59 + this.TimeOfRace.GetHashCode();
                if (this.FlagState != null)
                    hashCode = hashCode * 59 + this.FlagState.GetHashCode();
                if (this.Penalty != null)
                    hashCode = hashCode * 59 + this.Penalty.GetHashCode();
                if (this.Notes != null)
                    hashCode = hashCode * 59 + this.Notes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
