/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Represents a pit path associated with a track configuration, including its details and metadata.
    /// </summary>
    [DataContract]
        public partial class PitPath :  IEquatable<PitPath>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PitPath" /> class.
        /// </summary>
        /// <param name="id">Gets or sets the unique identifier for the pit path..</param>
        /// <param name="historyPitPathId">historyPitPathId.</param>
        /// <param name="trackConfigurationId">Gets or sets the identifier of the associated track configuration..</param>
        /// <param name="trackId">Gets or sets the unique identifier for the track..</param>
        /// <param name="name">Gets or sets the name of the pit path..</param>
        /// <param name="ordinalSortOrder">Gets or sets the ordinal sort order of the pit path..</param>
        /// <param name="pathData">Gets or sets the path data for the pit path..</param>
        /// <param name="length">Gets or sets the length of the pit path..</param>
        /// <param name="isPitIn">Gets or sets a value indicating whether the pit path is a \&quot;Pit In\&quot; path..</param>
        /// <param name="isPitOut">Gets or sets a value indicating whether the pit path is a \&quot;Pit Out\&quot; path..</param>
        public PitPath(int? id = default(int?), int? historyPitPathId = default(int?), int? trackConfigurationId = default(int?), int? trackId = default(int?), string name = default(string), int? ordinalSortOrder = default(int?), string pathData = default(string), int? length = default(int?), bool? isPitIn = default(bool?), bool? isPitOut = default(bool?))
        {
            this.Id = id;
            this.HistoryPitPathId = historyPitPathId;
            this.TrackConfigurationId = trackConfigurationId;
            this.TrackId = trackId;
            this.Name = name;
            this.OrdinalSortOrder = ordinalSortOrder;
            this.PathData = pathData;
            this.Length = length;
            this.IsPitIn = isPitIn;
            this.IsPitOut = isPitOut;
        }
        
        /// <summary>
        /// Gets or sets the unique identifier for the pit path.
        /// </summary>
        /// <value>Gets or sets the unique identifier for the pit path.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets HistoryPitPathId
        /// </summary>
        [DataMember(Name="history_pit_path_id", EmitDefaultValue=false)]
        public int? HistoryPitPathId { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the associated track configuration.
        /// </summary>
        /// <value>Gets or sets the identifier of the associated track configuration.</value>
        [DataMember(Name="track_configuration_id", EmitDefaultValue=false)]
        public int? TrackConfigurationId { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the track.
        /// </summary>
        /// <value>Gets or sets the unique identifier for the track.</value>
        [DataMember(Name="track_id", EmitDefaultValue=false)]
        public int? TrackId { get; set; }

        /// <summary>
        /// Gets or sets the name of the pit path.
        /// </summary>
        /// <value>Gets or sets the name of the pit path.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the ordinal sort order of the pit path.
        /// </summary>
        /// <value>Gets or sets the ordinal sort order of the pit path.</value>
        [DataMember(Name="ordinal_sort_order", EmitDefaultValue=false)]
        public int? OrdinalSortOrder { get; set; }

        /// <summary>
        /// Gets or sets the path data for the pit path.
        /// </summary>
        /// <value>Gets or sets the path data for the pit path.</value>
        [DataMember(Name="path_data", EmitDefaultValue=false)]
        public string PathData { get; set; }

        /// <summary>
        /// Gets or sets the length of the pit path.
        /// </summary>
        /// <value>Gets or sets the length of the pit path.</value>
        [DataMember(Name="length", EmitDefaultValue=false)]
        public int? Length { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the pit path is a \&quot;Pit In\&quot; path.
        /// </summary>
        /// <value>Gets or sets a value indicating whether the pit path is a \&quot;Pit In\&quot; path.</value>
        [DataMember(Name="is_pit_in", EmitDefaultValue=false)]
        public bool? IsPitIn { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the pit path is a \&quot;Pit Out\&quot; path.
        /// </summary>
        /// <value>Gets or sets a value indicating whether the pit path is a \&quot;Pit Out\&quot; path.</value>
        [DataMember(Name="is_pit_out", EmitDefaultValue=false)]
        public bool? IsPitOut { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PitPath {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  HistoryPitPathId: ").Append(HistoryPitPathId).Append("\n");
            sb.Append("  TrackConfigurationId: ").Append(TrackConfigurationId).Append("\n");
            sb.Append("  TrackId: ").Append(TrackId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OrdinalSortOrder: ").Append(OrdinalSortOrder).Append("\n");
            sb.Append("  PathData: ").Append(PathData).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  IsPitIn: ").Append(IsPitIn).Append("\n");
            sb.Append("  IsPitOut: ").Append(IsPitOut).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PitPath);
        }

        /// <summary>
        /// Returns true if PitPath instances are equal
        /// </summary>
        /// <param name="input">Instance of PitPath to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PitPath input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.HistoryPitPathId == input.HistoryPitPathId ||
                    (this.HistoryPitPathId != null &&
                    this.HistoryPitPathId.Equals(input.HistoryPitPathId))
                ) && 
                (
                    this.TrackConfigurationId == input.TrackConfigurationId ||
                    (this.TrackConfigurationId != null &&
                    this.TrackConfigurationId.Equals(input.TrackConfigurationId))
                ) && 
                (
                    this.TrackId == input.TrackId ||
                    (this.TrackId != null &&
                    this.TrackId.Equals(input.TrackId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.OrdinalSortOrder == input.OrdinalSortOrder ||
                    (this.OrdinalSortOrder != null &&
                    this.OrdinalSortOrder.Equals(input.OrdinalSortOrder))
                ) && 
                (
                    this.PathData == input.PathData ||
                    (this.PathData != null &&
                    this.PathData.Equals(input.PathData))
                ) && 
                (
                    this.Length == input.Length ||
                    (this.Length != null &&
                    this.Length.Equals(input.Length))
                ) && 
                (
                    this.IsPitIn == input.IsPitIn ||
                    (this.IsPitIn != null &&
                    this.IsPitIn.Equals(input.IsPitIn))
                ) && 
                (
                    this.IsPitOut == input.IsPitOut ||
                    (this.IsPitOut != null &&
                    this.IsPitOut.Equals(input.IsPitOut))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.HistoryPitPathId != null)
                    hashCode = hashCode * 59 + this.HistoryPitPathId.GetHashCode();
                if (this.TrackConfigurationId != null)
                    hashCode = hashCode * 59 + this.TrackConfigurationId.GetHashCode();
                if (this.TrackId != null)
                    hashCode = hashCode * 59 + this.TrackId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.OrdinalSortOrder != null)
                    hashCode = hashCode * 59 + this.OrdinalSortOrder.GetHashCode();
                if (this.PathData != null)
                    hashCode = hashCode * 59 + this.PathData.GetHashCode();
                if (this.Length != null)
                    hashCode = hashCode * 59 + this.Length.GetHashCode();
                if (this.IsPitIn != null)
                    hashCode = hashCode * 59 + this.IsPitIn.GetHashCode();
                if (this.IsPitOut != null)
                    hashCode = hashCode * 59 + this.IsPitOut.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
