/* 
 * NASCAR Data API
 *
 * Current & Preview API behavior.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Represents a pit stop event for a vehicle during a race run
    /// </summary>
    [DataContract]
        public partial class Pitstop :  IEquatable<Pitstop>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Pitstop" /> class.
        /// </summary>
        /// <param name="lap">Lap on which the pit stop occurred.</param>
        /// <param name="leaderLap">Lap of the leader when the pit stop occurred.</param>
        /// <param name="vehicleNumber">Vehicle number.</param>
        /// <param name="enterFlagState">Flag state on pit entry.</param>
        /// <param name="enterRaceTime">Enter race time (in milliseconds).</param>
        /// <param name="enterTravelDuration">Enter travel duration (in milliseconds).</param>
        /// <param name="adjustmentLeft">Left side adjustment made during pit stop.</param>
        /// <param name="adjustmentRight">Right side adjustment made during pit stop.</param>
        /// <param name="bodyRepairs">Body repairs performed during pit stop.</param>
        /// <param name="fuelCans">Number of fuel cans used during pit stop.</param>
        /// <param name="leftFrontTireChanged">Left front tire changed.</param>
        /// <param name="leftRearTireChanged">Left rear tire changed during pit stop.</param>
        /// <param name="rightFrontTireChanged">Right front tire changed during pit stop.</param>
        /// <param name="rightRearTireChanged">Right rear tire changed during pit stop.</param>
        /// <param name="infraction">Infraction issued during pit stop.</param>
        /// <param name="video">Video path associated with the pit stop.</param>
        /// <param name="pitBoxEnter">Pit box enter (in milliseconds).</param>
        /// <param name="pitBoxExit">Pit box exit (in milliseconds).</param>
        /// <param name="exitFlagState">Flag state on pit exit.</param>
        /// <param name="exitRaceTime">Exit race time (in milliseconds).</param>
        /// <param name="exitTravelDuration">Exit travel duration (in milliseconds).</param>
        /// <param name="totalDuration">Total time on pit road - from pit in loop to pit out loop (in milliseconds).</param>
        /// <param name="pitStopDuration">The time stopped in pit box (in milliseconds).</param>
        /// <param name="pitStopType">Description of pit stop (FOUR_TIRE_CHANGE, TWO_TIRE_CHANGE_RIGHT, etc).</param>
        /// <param name="pitInRank">Race rank when entering pit road.</param>
        /// <param name="pitOutRank">Race rank when exiting pit road.</param>
        /// <param name="positionsGainedLost">Number of positions gained or lost on this pit stop.</param>
        public Pitstop(int? lap = default(int?), int? leaderLap = default(int?), string vehicleNumber = default(string), int? enterFlagState = default(int?), double? enterRaceTime = default(double?), double? enterTravelDuration = default(double?), bool? adjustmentLeft = default(bool?), bool? adjustmentRight = default(bool?), bool? bodyRepairs = default(bool?), int? fuelCans = default(int?), bool? leftFrontTireChanged = default(bool?), bool? leftRearTireChanged = default(bool?), bool? rightFrontTireChanged = default(bool?), bool? rightRearTireChanged = default(bool?), string infraction = default(string), string video = default(string), double? pitBoxEnter = default(double?), double? pitBoxExit = default(double?), int? exitFlagState = default(int?), double? exitRaceTime = default(double?), double? exitTravelDuration = default(double?), double? totalDuration = default(double?), double? pitStopDuration = default(double?), string pitStopType = default(string), int? pitInRank = default(int?), int? pitOutRank = default(int?), int? positionsGainedLost = default(int?))
        {
            this.Lap = lap;
            this.LeaderLap = leaderLap;
            this.VehicleNumber = vehicleNumber;
            this.EnterFlagState = enterFlagState;
            this.EnterRaceTime = enterRaceTime;
            this.EnterTravelDuration = enterTravelDuration;
            this.AdjustmentLeft = adjustmentLeft;
            this.AdjustmentRight = adjustmentRight;
            this.BodyRepairs = bodyRepairs;
            this.FuelCans = fuelCans;
            this.LeftFrontTireChanged = leftFrontTireChanged;
            this.LeftRearTireChanged = leftRearTireChanged;
            this.RightFrontTireChanged = rightFrontTireChanged;
            this.RightRearTireChanged = rightRearTireChanged;
            this.Infraction = infraction;
            this.Video = video;
            this.PitBoxEnter = pitBoxEnter;
            this.PitBoxExit = pitBoxExit;
            this.ExitFlagState = exitFlagState;
            this.ExitRaceTime = exitRaceTime;
            this.ExitTravelDuration = exitTravelDuration;
            this.TotalDuration = totalDuration;
            this.PitStopDuration = pitStopDuration;
            this.PitStopType = pitStopType;
            this.PitInRank = pitInRank;
            this.PitOutRank = pitOutRank;
            this.PositionsGainedLost = positionsGainedLost;
        }
        
        /// <summary>
        /// Lap on which the pit stop occurred
        /// </summary>
        /// <value>Lap on which the pit stop occurred</value>
        [DataMember(Name="lap", EmitDefaultValue=false)]
        public int? Lap { get; set; }

        /// <summary>
        /// Lap of the leader when the pit stop occurred
        /// </summary>
        /// <value>Lap of the leader when the pit stop occurred</value>
        [DataMember(Name="leader_lap", EmitDefaultValue=false)]
        public int? LeaderLap { get; set; }

        /// <summary>
        /// Vehicle number
        /// </summary>
        /// <value>Vehicle number</value>
        [DataMember(Name="vehicle_number", EmitDefaultValue=false)]
        public string VehicleNumber { get; set; }

        /// <summary>
        /// Flag state on pit entry
        /// </summary>
        /// <value>Flag state on pit entry</value>
        [DataMember(Name="enter_flag_state", EmitDefaultValue=false)]
        public int? EnterFlagState { get; set; }

        /// <summary>
        /// Enter race time (in milliseconds)
        /// </summary>
        /// <value>Enter race time (in milliseconds)</value>
        [DataMember(Name="enter_race_time", EmitDefaultValue=false)]
        public double? EnterRaceTime { get; set; }

        /// <summary>
        /// Enter travel duration (in milliseconds)
        /// </summary>
        /// <value>Enter travel duration (in milliseconds)</value>
        [DataMember(Name="enter_travel_duration", EmitDefaultValue=false)]
        public double? EnterTravelDuration { get; set; }

        /// <summary>
        /// Left side adjustment made during pit stop
        /// </summary>
        /// <value>Left side adjustment made during pit stop</value>
        [DataMember(Name="adjustment_left", EmitDefaultValue=false)]
        public bool? AdjustmentLeft { get; set; }

        /// <summary>
        /// Right side adjustment made during pit stop
        /// </summary>
        /// <value>Right side adjustment made during pit stop</value>
        [DataMember(Name="adjustment_right", EmitDefaultValue=false)]
        public bool? AdjustmentRight { get; set; }

        /// <summary>
        /// Body repairs performed during pit stop
        /// </summary>
        /// <value>Body repairs performed during pit stop</value>
        [DataMember(Name="body_repairs", EmitDefaultValue=false)]
        public bool? BodyRepairs { get; set; }

        /// <summary>
        /// Number of fuel cans used during pit stop
        /// </summary>
        /// <value>Number of fuel cans used during pit stop</value>
        [DataMember(Name="fuel_cans", EmitDefaultValue=false)]
        public int? FuelCans { get; set; }

        /// <summary>
        /// Left front tire changed
        /// </summary>
        /// <value>Left front tire changed</value>
        [DataMember(Name="left_front_tire_changed", EmitDefaultValue=false)]
        public bool? LeftFrontTireChanged { get; set; }

        /// <summary>
        /// Left rear tire changed during pit stop
        /// </summary>
        /// <value>Left rear tire changed during pit stop</value>
        [DataMember(Name="left_rear_tire_changed", EmitDefaultValue=false)]
        public bool? LeftRearTireChanged { get; set; }

        /// <summary>
        /// Right front tire changed during pit stop
        /// </summary>
        /// <value>Right front tire changed during pit stop</value>
        [DataMember(Name="right_front_tire_changed", EmitDefaultValue=false)]
        public bool? RightFrontTireChanged { get; set; }

        /// <summary>
        /// Right rear tire changed during pit stop
        /// </summary>
        /// <value>Right rear tire changed during pit stop</value>
        [DataMember(Name="right_rear_tire_changed", EmitDefaultValue=false)]
        public bool? RightRearTireChanged { get; set; }

        /// <summary>
        /// Infraction issued during pit stop
        /// </summary>
        /// <value>Infraction issued during pit stop</value>
        [DataMember(Name="infraction", EmitDefaultValue=false)]
        public string Infraction { get; set; }

        /// <summary>
        /// Video path associated with the pit stop
        /// </summary>
        /// <value>Video path associated with the pit stop</value>
        [DataMember(Name="video", EmitDefaultValue=false)]
        public string Video { get; set; }

        /// <summary>
        /// Pit box enter (in milliseconds)
        /// </summary>
        /// <value>Pit box enter (in milliseconds)</value>
        [DataMember(Name="pit_box_enter", EmitDefaultValue=false)]
        public double? PitBoxEnter { get; set; }

        /// <summary>
        /// Pit box exit (in milliseconds)
        /// </summary>
        /// <value>Pit box exit (in milliseconds)</value>
        [DataMember(Name="pit_box_exit", EmitDefaultValue=false)]
        public double? PitBoxExit { get; set; }

        /// <summary>
        /// Flag state on pit exit
        /// </summary>
        /// <value>Flag state on pit exit</value>
        [DataMember(Name="exit_flag_state", EmitDefaultValue=false)]
        public int? ExitFlagState { get; set; }

        /// <summary>
        /// Exit race time (in milliseconds)
        /// </summary>
        /// <value>Exit race time (in milliseconds)</value>
        [DataMember(Name="exit_race_time", EmitDefaultValue=false)]
        public double? ExitRaceTime { get; set; }

        /// <summary>
        /// Exit travel duration (in milliseconds)
        /// </summary>
        /// <value>Exit travel duration (in milliseconds)</value>
        [DataMember(Name="exit_travel_duration", EmitDefaultValue=false)]
        public double? ExitTravelDuration { get; set; }

        /// <summary>
        /// Total time on pit road - from pit in loop to pit out loop (in milliseconds)
        /// </summary>
        /// <value>Total time on pit road - from pit in loop to pit out loop (in milliseconds)</value>
        [DataMember(Name="total_duration", EmitDefaultValue=false)]
        public double? TotalDuration { get; set; }

        /// <summary>
        /// The time stopped in pit box (in milliseconds)
        /// </summary>
        /// <value>The time stopped in pit box (in milliseconds)</value>
        [DataMember(Name="pit_stop_duration", EmitDefaultValue=false)]
        public double? PitStopDuration { get; set; }

        /// <summary>
        /// Description of pit stop (FOUR_TIRE_CHANGE, TWO_TIRE_CHANGE_RIGHT, etc)
        /// </summary>
        /// <value>Description of pit stop (FOUR_TIRE_CHANGE, TWO_TIRE_CHANGE_RIGHT, etc)</value>
        [DataMember(Name="pit_stop_type", EmitDefaultValue=false)]
        public string PitStopType { get; set; }

        /// <summary>
        /// Race rank when entering pit road
        /// </summary>
        /// <value>Race rank when entering pit road</value>
        [DataMember(Name="pit_in_rank", EmitDefaultValue=false)]
        public int? PitInRank { get; set; }

        /// <summary>
        /// Race rank when exiting pit road
        /// </summary>
        /// <value>Race rank when exiting pit road</value>
        [DataMember(Name="pit_out_rank", EmitDefaultValue=false)]
        public int? PitOutRank { get; set; }

        /// <summary>
        /// Number of positions gained or lost on this pit stop
        /// </summary>
        /// <value>Number of positions gained or lost on this pit stop</value>
        [DataMember(Name="positions_gained_lost", EmitDefaultValue=false)]
        public int? PositionsGainedLost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Pitstop {\n");
            sb.Append("  Lap: ").Append(Lap).Append("\n");
            sb.Append("  LeaderLap: ").Append(LeaderLap).Append("\n");
            sb.Append("  VehicleNumber: ").Append(VehicleNumber).Append("\n");
            sb.Append("  EnterFlagState: ").Append(EnterFlagState).Append("\n");
            sb.Append("  EnterRaceTime: ").Append(EnterRaceTime).Append("\n");
            sb.Append("  EnterTravelDuration: ").Append(EnterTravelDuration).Append("\n");
            sb.Append("  AdjustmentLeft: ").Append(AdjustmentLeft).Append("\n");
            sb.Append("  AdjustmentRight: ").Append(AdjustmentRight).Append("\n");
            sb.Append("  BodyRepairs: ").Append(BodyRepairs).Append("\n");
            sb.Append("  FuelCans: ").Append(FuelCans).Append("\n");
            sb.Append("  LeftFrontTireChanged: ").Append(LeftFrontTireChanged).Append("\n");
            sb.Append("  LeftRearTireChanged: ").Append(LeftRearTireChanged).Append("\n");
            sb.Append("  RightFrontTireChanged: ").Append(RightFrontTireChanged).Append("\n");
            sb.Append("  RightRearTireChanged: ").Append(RightRearTireChanged).Append("\n");
            sb.Append("  Infraction: ").Append(Infraction).Append("\n");
            sb.Append("  Video: ").Append(Video).Append("\n");
            sb.Append("  PitBoxEnter: ").Append(PitBoxEnter).Append("\n");
            sb.Append("  PitBoxExit: ").Append(PitBoxExit).Append("\n");
            sb.Append("  ExitFlagState: ").Append(ExitFlagState).Append("\n");
            sb.Append("  ExitRaceTime: ").Append(ExitRaceTime).Append("\n");
            sb.Append("  ExitTravelDuration: ").Append(ExitTravelDuration).Append("\n");
            sb.Append("  TotalDuration: ").Append(TotalDuration).Append("\n");
            sb.Append("  PitStopDuration: ").Append(PitStopDuration).Append("\n");
            sb.Append("  PitStopType: ").Append(PitStopType).Append("\n");
            sb.Append("  PitInRank: ").Append(PitInRank).Append("\n");
            sb.Append("  PitOutRank: ").Append(PitOutRank).Append("\n");
            sb.Append("  PositionsGainedLost: ").Append(PositionsGainedLost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Pitstop);
        }

        /// <summary>
        /// Returns true if Pitstop instances are equal
        /// </summary>
        /// <param name="input">Instance of Pitstop to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Pitstop input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Lap == input.Lap ||
                    (this.Lap != null &&
                    this.Lap.Equals(input.Lap))
                ) && 
                (
                    this.LeaderLap == input.LeaderLap ||
                    (this.LeaderLap != null &&
                    this.LeaderLap.Equals(input.LeaderLap))
                ) && 
                (
                    this.VehicleNumber == input.VehicleNumber ||
                    (this.VehicleNumber != null &&
                    this.VehicleNumber.Equals(input.VehicleNumber))
                ) && 
                (
                    this.EnterFlagState == input.EnterFlagState ||
                    (this.EnterFlagState != null &&
                    this.EnterFlagState.Equals(input.EnterFlagState))
                ) && 
                (
                    this.EnterRaceTime == input.EnterRaceTime ||
                    (this.EnterRaceTime != null &&
                    this.EnterRaceTime.Equals(input.EnterRaceTime))
                ) && 
                (
                    this.EnterTravelDuration == input.EnterTravelDuration ||
                    (this.EnterTravelDuration != null &&
                    this.EnterTravelDuration.Equals(input.EnterTravelDuration))
                ) && 
                (
                    this.AdjustmentLeft == input.AdjustmentLeft ||
                    (this.AdjustmentLeft != null &&
                    this.AdjustmentLeft.Equals(input.AdjustmentLeft))
                ) && 
                (
                    this.AdjustmentRight == input.AdjustmentRight ||
                    (this.AdjustmentRight != null &&
                    this.AdjustmentRight.Equals(input.AdjustmentRight))
                ) && 
                (
                    this.BodyRepairs == input.BodyRepairs ||
                    (this.BodyRepairs != null &&
                    this.BodyRepairs.Equals(input.BodyRepairs))
                ) && 
                (
                    this.FuelCans == input.FuelCans ||
                    (this.FuelCans != null &&
                    this.FuelCans.Equals(input.FuelCans))
                ) && 
                (
                    this.LeftFrontTireChanged == input.LeftFrontTireChanged ||
                    (this.LeftFrontTireChanged != null &&
                    this.LeftFrontTireChanged.Equals(input.LeftFrontTireChanged))
                ) && 
                (
                    this.LeftRearTireChanged == input.LeftRearTireChanged ||
                    (this.LeftRearTireChanged != null &&
                    this.LeftRearTireChanged.Equals(input.LeftRearTireChanged))
                ) && 
                (
                    this.RightFrontTireChanged == input.RightFrontTireChanged ||
                    (this.RightFrontTireChanged != null &&
                    this.RightFrontTireChanged.Equals(input.RightFrontTireChanged))
                ) && 
                (
                    this.RightRearTireChanged == input.RightRearTireChanged ||
                    (this.RightRearTireChanged != null &&
                    this.RightRearTireChanged.Equals(input.RightRearTireChanged))
                ) && 
                (
                    this.Infraction == input.Infraction ||
                    (this.Infraction != null &&
                    this.Infraction.Equals(input.Infraction))
                ) && 
                (
                    this.Video == input.Video ||
                    (this.Video != null &&
                    this.Video.Equals(input.Video))
                ) && 
                (
                    this.PitBoxEnter == input.PitBoxEnter ||
                    (this.PitBoxEnter != null &&
                    this.PitBoxEnter.Equals(input.PitBoxEnter))
                ) && 
                (
                    this.PitBoxExit == input.PitBoxExit ||
                    (this.PitBoxExit != null &&
                    this.PitBoxExit.Equals(input.PitBoxExit))
                ) && 
                (
                    this.ExitFlagState == input.ExitFlagState ||
                    (this.ExitFlagState != null &&
                    this.ExitFlagState.Equals(input.ExitFlagState))
                ) && 
                (
                    this.ExitRaceTime == input.ExitRaceTime ||
                    (this.ExitRaceTime != null &&
                    this.ExitRaceTime.Equals(input.ExitRaceTime))
                ) && 
                (
                    this.ExitTravelDuration == input.ExitTravelDuration ||
                    (this.ExitTravelDuration != null &&
                    this.ExitTravelDuration.Equals(input.ExitTravelDuration))
                ) && 
                (
                    this.TotalDuration == input.TotalDuration ||
                    (this.TotalDuration != null &&
                    this.TotalDuration.Equals(input.TotalDuration))
                ) && 
                (
                    this.PitStopDuration == input.PitStopDuration ||
                    (this.PitStopDuration != null &&
                    this.PitStopDuration.Equals(input.PitStopDuration))
                ) && 
                (
                    this.PitStopType == input.PitStopType ||
                    (this.PitStopType != null &&
                    this.PitStopType.Equals(input.PitStopType))
                ) && 
                (
                    this.PitInRank == input.PitInRank ||
                    (this.PitInRank != null &&
                    this.PitInRank.Equals(input.PitInRank))
                ) && 
                (
                    this.PitOutRank == input.PitOutRank ||
                    (this.PitOutRank != null &&
                    this.PitOutRank.Equals(input.PitOutRank))
                ) && 
                (
                    this.PositionsGainedLost == input.PositionsGainedLost ||
                    (this.PositionsGainedLost != null &&
                    this.PositionsGainedLost.Equals(input.PositionsGainedLost))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Lap != null)
                    hashCode = hashCode * 59 + this.Lap.GetHashCode();
                if (this.LeaderLap != null)
                    hashCode = hashCode * 59 + this.LeaderLap.GetHashCode();
                if (this.VehicleNumber != null)
                    hashCode = hashCode * 59 + this.VehicleNumber.GetHashCode();
                if (this.EnterFlagState != null)
                    hashCode = hashCode * 59 + this.EnterFlagState.GetHashCode();
                if (this.EnterRaceTime != null)
                    hashCode = hashCode * 59 + this.EnterRaceTime.GetHashCode();
                if (this.EnterTravelDuration != null)
                    hashCode = hashCode * 59 + this.EnterTravelDuration.GetHashCode();
                if (this.AdjustmentLeft != null)
                    hashCode = hashCode * 59 + this.AdjustmentLeft.GetHashCode();
                if (this.AdjustmentRight != null)
                    hashCode = hashCode * 59 + this.AdjustmentRight.GetHashCode();
                if (this.BodyRepairs != null)
                    hashCode = hashCode * 59 + this.BodyRepairs.GetHashCode();
                if (this.FuelCans != null)
                    hashCode = hashCode * 59 + this.FuelCans.GetHashCode();
                if (this.LeftFrontTireChanged != null)
                    hashCode = hashCode * 59 + this.LeftFrontTireChanged.GetHashCode();
                if (this.LeftRearTireChanged != null)
                    hashCode = hashCode * 59 + this.LeftRearTireChanged.GetHashCode();
                if (this.RightFrontTireChanged != null)
                    hashCode = hashCode * 59 + this.RightFrontTireChanged.GetHashCode();
                if (this.RightRearTireChanged != null)
                    hashCode = hashCode * 59 + this.RightRearTireChanged.GetHashCode();
                if (this.Infraction != null)
                    hashCode = hashCode * 59 + this.Infraction.GetHashCode();
                if (this.Video != null)
                    hashCode = hashCode * 59 + this.Video.GetHashCode();
                if (this.PitBoxEnter != null)
                    hashCode = hashCode * 59 + this.PitBoxEnter.GetHashCode();
                if (this.PitBoxExit != null)
                    hashCode = hashCode * 59 + this.PitBoxExit.GetHashCode();
                if (this.ExitFlagState != null)
                    hashCode = hashCode * 59 + this.ExitFlagState.GetHashCode();
                if (this.ExitRaceTime != null)
                    hashCode = hashCode * 59 + this.ExitRaceTime.GetHashCode();
                if (this.ExitTravelDuration != null)
                    hashCode = hashCode * 59 + this.ExitTravelDuration.GetHashCode();
                if (this.TotalDuration != null)
                    hashCode = hashCode * 59 + this.TotalDuration.GetHashCode();
                if (this.PitStopDuration != null)
                    hashCode = hashCode * 59 + this.PitStopDuration.GetHashCode();
                if (this.PitStopType != null)
                    hashCode = hashCode * 59 + this.PitStopType.GetHashCode();
                if (this.PitInRank != null)
                    hashCode = hashCode * 59 + this.PitInRank.GetHashCode();
                if (this.PitOutRank != null)
                    hashCode = hashCode * 59 + this.PitOutRank.GetHashCode();
                if (this.PositionsGainedLost != null)
                    hashCode = hashCode * 59 + this.PositionsGainedLost.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
