/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// ProcessingState
    /// </summary>
    [DataContract]
        public partial class ProcessingState :  IEquatable<ProcessingState>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessingState" /> class.
        /// </summary>
        /// <param name="category">category.</param>
        /// <param name="intervalInSeconds">intervalInSeconds.</param>
        /// <param name="action">action.</param>
        /// <param name="lastRun">lastRun.</param>
        /// <param name="actionDetailId">actionDetailId.</param>
        /// <param name="value">value.</param>
        /// <param name="isActive">isActive.</param>
        public ProcessingState(string category = default(string), int? intervalInSeconds = default(int?), string action = default(string), DateTimeOffset? lastRun = default(DateTimeOffset?), int? actionDetailId = default(int?), int? value = default(int?), bool? isActive = default(bool?))
        {
            this.Category = category;
            this.IntervalInSeconds = intervalInSeconds;
            this.Action = action;
            this.LastRun = lastRun;
            this.ActionDetailId = actionDetailId;
            this.Value = value;
            this.IsActive = isActive;
        }
        
        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="Category", EmitDefaultValue=false)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets IntervalInSeconds
        /// </summary>
        [DataMember(Name="IntervalInSeconds", EmitDefaultValue=false)]
        public int? IntervalInSeconds { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="Action", EmitDefaultValue=false)]
        public string Action { get; set; }

        /// <summary>
        /// Gets or Sets LastRun
        /// </summary>
        [DataMember(Name="LastRun", EmitDefaultValue=false)]
        public DateTimeOffset? LastRun { get; set; }

        /// <summary>
        /// Gets or Sets ActionDetailId
        /// </summary>
        [DataMember(Name="ActionDetailId", EmitDefaultValue=false)]
        public int? ActionDetailId { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="Value", EmitDefaultValue=false)]
        public int? Value { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name="IsActive", EmitDefaultValue=false)]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProcessingState {\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  IntervalInSeconds: ").Append(IntervalInSeconds).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  LastRun: ").Append(LastRun).Append("\n");
            sb.Append("  ActionDetailId: ").Append(ActionDetailId).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProcessingState);
        }

        /// <summary>
        /// Returns true if ProcessingState instances are equal
        /// </summary>
        /// <param name="input">Instance of ProcessingState to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProcessingState input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.IntervalInSeconds == input.IntervalInSeconds ||
                    (this.IntervalInSeconds != null &&
                    this.IntervalInSeconds.Equals(input.IntervalInSeconds))
                ) && 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.LastRun == input.LastRun ||
                    (this.LastRun != null &&
                    this.LastRun.Equals(input.LastRun))
                ) && 
                (
                    this.ActionDetailId == input.ActionDetailId ||
                    (this.ActionDetailId != null &&
                    this.ActionDetailId.Equals(input.ActionDetailId))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.IsActive == input.IsActive ||
                    (this.IsActive != null &&
                    this.IsActive.Equals(input.IsActive))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.IntervalInSeconds != null)
                    hashCode = hashCode * 59 + this.IntervalInSeconds.GetHashCode();
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.LastRun != null)
                    hashCode = hashCode * 59 + this.LastRun.GetHashCode();
                if (this.ActionDetailId != null)
                    hashCode = hashCode * 59 + this.ActionDetailId.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.IsActive != null)
                    hashCode = hashCode * 59 + this.IsActive.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
