/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Race
    /// </summary>
    [DataContract]
        public partial class Race :  IEquatable<Race>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Race" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="principalRaceId">principalRaceId.</param>
        /// <param name="eventId">eventId.</param>
        /// <param name="seriesId">seriesId.</param>
        /// <param name="name">name.</param>
        /// <param name="promoter">promoter.</param>
        /// <param name="laps">laps.</param>
        /// <param name="distance">distance.</param>
        /// <param name="date">date.</param>
        /// <param name="comments">comments.</param>
        public Race(int? id = default(int?), int? principalRaceId = default(int?), int? eventId = default(int?), int? seriesId = default(int?), string name = default(string), string promoter = default(string), int? laps = default(int?), double? distance = default(double?), DateTimeOffset? date = default(DateTimeOffset?), string comments = default(string))
        {
            this.Id = id;
            this.PrincipalRaceId = principalRaceId;
            this.EventId = eventId;
            this.SeriesId = seriesId;
            this.Name = name;
            this.Promoter = promoter;
            this.Laps = laps;
            this.Distance = distance;
            this.Date = date;
            this.Comments = comments;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets PrincipalRaceId
        /// </summary>
        [DataMember(Name="principal_race_id", EmitDefaultValue=false)]
        public int? PrincipalRaceId { get; set; }

        /// <summary>
        /// Gets or Sets EventId
        /// </summary>
        [DataMember(Name="event_id", EmitDefaultValue=false)]
        public int? EventId { get; set; }

        /// <summary>
        /// Gets or Sets SeriesId
        /// </summary>
        [DataMember(Name="series_id", EmitDefaultValue=false)]
        public int? SeriesId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Promoter
        /// </summary>
        [DataMember(Name="promoter", EmitDefaultValue=false)]
        public string Promoter { get; set; }

        /// <summary>
        /// Gets or Sets Laps
        /// </summary>
        [DataMember(Name="laps", EmitDefaultValue=false)]
        public int? Laps { get; set; }

        /// <summary>
        /// Gets or Sets Distance
        /// </summary>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public double? Distance { get; set; }

        /// <summary>
        /// Gets or Sets PracticeResults
        /// </summary>
        [DataMember(Name="practice_results", EmitDefaultValue=false)]
        public string PracticeResults { get; private set; }

        /// <summary>
        /// Gets or Sets QualifyingResults
        /// </summary>
        [DataMember(Name="qualifying_results", EmitDefaultValue=false)]
        public string QualifyingResults { get; private set; }

        /// <summary>
        /// Gets or Sets RaceResults
        /// </summary>
        [DataMember(Name="race_results", EmitDefaultValue=false)]
        public string RaceResults { get; private set; }

        /// <summary>
        /// Gets or Sets Cautions
        /// </summary>
        [DataMember(Name="cautions", EmitDefaultValue=false)]
        public string Cautions { get; private set; }

        /// <summary>
        /// Gets or Sets Infractions
        /// </summary>
        [DataMember(Name="infractions", EmitDefaultValue=false)]
        public string Infractions { get; private set; }

        /// <summary>
        /// Gets or Sets LapLeaders
        /// </summary>
        [DataMember(Name="lap_leaders", EmitDefaultValue=false)]
        public string LapLeaders { get; private set; }

        /// <summary>
        /// Gets or Sets Pitstops
        /// </summary>
        [DataMember(Name="pitstops", EmitDefaultValue=false)]
        public string Pitstops { get; private set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public DateTimeOffset? Date { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public string Comments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Race {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PrincipalRaceId: ").Append(PrincipalRaceId).Append("\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  SeriesId: ").Append(SeriesId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Promoter: ").Append(Promoter).Append("\n");
            sb.Append("  Laps: ").Append(Laps).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  PracticeResults: ").Append(PracticeResults).Append("\n");
            sb.Append("  QualifyingResults: ").Append(QualifyingResults).Append("\n");
            sb.Append("  RaceResults: ").Append(RaceResults).Append("\n");
            sb.Append("  Cautions: ").Append(Cautions).Append("\n");
            sb.Append("  Infractions: ").Append(Infractions).Append("\n");
            sb.Append("  LapLeaders: ").Append(LapLeaders).Append("\n");
            sb.Append("  Pitstops: ").Append(Pitstops).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Race);
        }

        /// <summary>
        /// Returns true if Race instances are equal
        /// </summary>
        /// <param name="input">Instance of Race to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Race input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.PrincipalRaceId == input.PrincipalRaceId ||
                    (this.PrincipalRaceId != null &&
                    this.PrincipalRaceId.Equals(input.PrincipalRaceId))
                ) && 
                (
                    this.EventId == input.EventId ||
                    (this.EventId != null &&
                    this.EventId.Equals(input.EventId))
                ) && 
                (
                    this.SeriesId == input.SeriesId ||
                    (this.SeriesId != null &&
                    this.SeriesId.Equals(input.SeriesId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Promoter == input.Promoter ||
                    (this.Promoter != null &&
                    this.Promoter.Equals(input.Promoter))
                ) && 
                (
                    this.Laps == input.Laps ||
                    (this.Laps != null &&
                    this.Laps.Equals(input.Laps))
                ) && 
                (
                    this.Distance == input.Distance ||
                    (this.Distance != null &&
                    this.Distance.Equals(input.Distance))
                ) && 
                (
                    this.PracticeResults == input.PracticeResults ||
                    (this.PracticeResults != null &&
                    this.PracticeResults.Equals(input.PracticeResults))
                ) && 
                (
                    this.QualifyingResults == input.QualifyingResults ||
                    (this.QualifyingResults != null &&
                    this.QualifyingResults.Equals(input.QualifyingResults))
                ) && 
                (
                    this.RaceResults == input.RaceResults ||
                    (this.RaceResults != null &&
                    this.RaceResults.Equals(input.RaceResults))
                ) && 
                (
                    this.Cautions == input.Cautions ||
                    (this.Cautions != null &&
                    this.Cautions.Equals(input.Cautions))
                ) && 
                (
                    this.Infractions == input.Infractions ||
                    (this.Infractions != null &&
                    this.Infractions.Equals(input.Infractions))
                ) && 
                (
                    this.LapLeaders == input.LapLeaders ||
                    (this.LapLeaders != null &&
                    this.LapLeaders.Equals(input.LapLeaders))
                ) && 
                (
                    this.Pitstops == input.Pitstops ||
                    (this.Pitstops != null &&
                    this.Pitstops.Equals(input.Pitstops))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.PrincipalRaceId != null)
                    hashCode = hashCode * 59 + this.PrincipalRaceId.GetHashCode();
                if (this.EventId != null)
                    hashCode = hashCode * 59 + this.EventId.GetHashCode();
                if (this.SeriesId != null)
                    hashCode = hashCode * 59 + this.SeriesId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Promoter != null)
                    hashCode = hashCode * 59 + this.Promoter.GetHashCode();
                if (this.Laps != null)
                    hashCode = hashCode * 59 + this.Laps.GetHashCode();
                if (this.Distance != null)
                    hashCode = hashCode * 59 + this.Distance.GetHashCode();
                if (this.PracticeResults != null)
                    hashCode = hashCode * 59 + this.PracticeResults.GetHashCode();
                if (this.QualifyingResults != null)
                    hashCode = hashCode * 59 + this.QualifyingResults.GetHashCode();
                if (this.RaceResults != null)
                    hashCode = hashCode * 59 + this.RaceResults.GetHashCode();
                if (this.Cautions != null)
                    hashCode = hashCode * 59 + this.Cautions.GetHashCode();
                if (this.Infractions != null)
                    hashCode = hashCode * 59 + this.Infractions.GetHashCode();
                if (this.LapLeaders != null)
                    hashCode = hashCode * 59 + this.LapLeaders.GetHashCode();
                if (this.Pitstops != null)
                    hashCode = hashCode * 59 + this.Pitstops.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
