/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Represents a NASCAR race event and its associated metadata
    /// </summary>
    [DataContract]
        public partial class Race :  IEquatable<Race>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Race" /> class.
        /// </summary>
        /// <param name="id">Unique identifier given and used by the NASCAR Data API.</param>
        /// <param name="principalRaceId">Principal race identifier.</param>
        /// <param name="historyRaceId">Historical race identifier (default to -1).</param>
        /// <param name="raceweekId">Associated race week event identifier.</param>
        /// <param name="seriesId">Series identifier.</param>
        /// <param name="name">Race name.</param>
        /// <param name="raceTypeId">Race Type Identifier (1-Race, 2-Duel, 3-Heat, 4-Exhibition).</param>
        /// <param name="raceNumber">Race number within the season/series schedule.</param>
        /// <param name="restrictorPlate">Indicates whether restrictor plates are required for this race.</param>
        /// <param name="totalRaceTime">String formatted representation of the total time of race HH:MM:SS.</param>
        /// <param name="promoter">Promoter of the race.</param>
        /// <param name="laps">Scheduled number of laps for this race.</param>
        /// <param name="actualLaps">Actual number of laps for this race.</param>
        /// <param name="distance">Scheduled distance for this race in miles.</param>
        /// <param name="actualDistance">Actual distance for this race in miles.</param>
        /// <param name="inspectionComplete">Indicates whether inspection has been completed.</param>
        /// <param name="numberOfCarsInField">Number of cars in this race.</param>
        /// <param name="poleWinnerDriverId">API Driver ID for the driver who won the pole for this race.</param>
        /// <param name="poleWinnerSpeed">Lap speed for the pole winner.</param>
        /// <param name="numberOfLeadChanges">Number of times the leader changed (Start Finish based) for this race.</param>
        /// <param name="numberOfLeaders">Number of distinct leaders (Start Finish based) for this race.</param>
        /// <param name="averageSpeed">Average speed of this race.</param>
        /// <param name="marginOfVictory">String representation of the margin of victory.  May be the time between 1st and 2nd place finishers or Caution if the race ended under caution..</param>
        /// <param name="radioBroadcaster">Name of radio broadcaster for this race.</param>
        /// <param name="televisionBroadcaster">Name of television broadcaster for this race.</param>
        /// <param name="satelliteRadioBroadcaster">Name of satellite radio broadcaster for this race.</param>
        /// <param name="playoffRound">Round of the playoffs that this race is a part of, 0 for non-playoff races.</param>
        /// <param name="isQualifyingRace">Indicates when run is a qualifying race.</param>
        /// <param name="qualifyingRaceNo">Sequence number of qualifying race.</param>
        /// <param name="qualifyingRaceId">ID of qualifying race.</param>
        /// <param name="hasQualifying">Indicates whether this race has qualifying.</param>
        /// <param name="date">Race date.</param>
        /// <param name="qualifyingDate">Date qualifying was held for this race.</param>
        /// <param name="comments">Race comments.</param>
        /// <param name="historyTrackId">Historical track identifier.</param>
        /// <param name="trackId">Track identifier.</param>
        /// <param name="fastestLapAward">fastestLapAward.</param>
        public Race(int? id = default(int?), int? principalRaceId = default(int?), int? historyRaceId = -1, int? raceweekId = default(int?), int? seriesId = default(int?), string name = default(string), int? raceTypeId = default(int?), int? raceNumber = default(int?), bool? restrictorPlate = default(bool?), string totalRaceTime = default(string), string promoter = default(string), int? laps = default(int?), int? actualLaps = default(int?), double? distance = default(double?), double? actualDistance = default(double?), bool? inspectionComplete = default(bool?), int? numberOfCarsInField = default(int?), int? poleWinnerDriverId = default(int?), double? poleWinnerSpeed = default(double?), int? numberOfLeadChanges = default(int?), int? numberOfLeaders = default(int?), double? averageSpeed = default(double?), string marginOfVictory = default(string), string radioBroadcaster = default(string), string televisionBroadcaster = default(string), string satelliteRadioBroadcaster = default(string), int? playoffRound = default(int?), bool? isQualifyingRace = default(bool?), int? qualifyingRaceNo = default(int?), int? qualifyingRaceId = default(int?), bool? hasQualifying = default(bool?), DateTimeOffset? date = default(DateTimeOffset?), DateTimeOffset? qualifyingDate = default(DateTimeOffset?), string comments = default(string), int? historyTrackId = default(int?), int? trackId = default(int?), FastestLapAwards fastestLapAward = default(FastestLapAwards))
        {
            this.Id = id;
            this.PrincipalRaceId = principalRaceId;
            // use default value if no "historyRaceId" provided
            if (historyRaceId == null)
            {
                this.HistoryRaceId = -1;
            }
            else
            {
                this.HistoryRaceId = historyRaceId;
            }
            this.RaceweekId = raceweekId;
            this.SeriesId = seriesId;
            this.Name = name;
            this.RaceTypeId = raceTypeId;
            this.RaceNumber = raceNumber;
            this.RestrictorPlate = restrictorPlate;
            this.TotalRaceTime = totalRaceTime;
            this.Promoter = promoter;
            this.Laps = laps;
            this.ActualLaps = actualLaps;
            this.Distance = distance;
            this.ActualDistance = actualDistance;
            this.InspectionComplete = inspectionComplete;
            this.NumberOfCarsInField = numberOfCarsInField;
            this.PoleWinnerDriverId = poleWinnerDriverId;
            this.PoleWinnerSpeed = poleWinnerSpeed;
            this.NumberOfLeadChanges = numberOfLeadChanges;
            this.NumberOfLeaders = numberOfLeaders;
            this.AverageSpeed = averageSpeed;
            this.MarginOfVictory = marginOfVictory;
            this.RadioBroadcaster = radioBroadcaster;
            this.TelevisionBroadcaster = televisionBroadcaster;
            this.SatelliteRadioBroadcaster = satelliteRadioBroadcaster;
            this.PlayoffRound = playoffRound;
            this.IsQualifyingRace = isQualifyingRace;
            this.QualifyingRaceNo = qualifyingRaceNo;
            this.QualifyingRaceId = qualifyingRaceId;
            this.HasQualifying = hasQualifying;
            this.Date = date;
            this.QualifyingDate = qualifyingDate;
            this.Comments = comments;
            this.HistoryTrackId = historyTrackId;
            this.TrackId = trackId;
            this.FastestLapAward = fastestLapAward;
        }
        
        /// <summary>
        /// Unique identifier given and used by the NASCAR Data API
        /// </summary>
        /// <value>Unique identifier given and used by the NASCAR Data API</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Principal race identifier
        /// </summary>
        /// <value>Principal race identifier</value>
        [DataMember(Name="principal_race_id", EmitDefaultValue=false)]
        public int? PrincipalRaceId { get; set; }

        /// <summary>
        /// Historical race identifier
        /// </summary>
        /// <value>Historical race identifier</value>
        [DataMember(Name="history_race_id", EmitDefaultValue=false)]
        public int? HistoryRaceId { get; set; }

        /// <summary>
        /// Associated race week event identifier
        /// </summary>
        /// <value>Associated race week event identifier</value>
        [DataMember(Name="raceweek_id", EmitDefaultValue=false)]
        public int? RaceweekId { get; set; }

        /// <summary>
        /// Series identifier
        /// </summary>
        /// <value>Series identifier</value>
        [DataMember(Name="series_id", EmitDefaultValue=false)]
        public int? SeriesId { get; set; }

        /// <summary>
        /// Race name
        /// </summary>
        /// <value>Race name</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Race Type Identifier (1-Race, 2-Duel, 3-Heat, 4-Exhibition)
        /// </summary>
        /// <value>Race Type Identifier (1-Race, 2-Duel, 3-Heat, 4-Exhibition)</value>
        [DataMember(Name="race_type_id", EmitDefaultValue=false)]
        public int? RaceTypeId { get; set; }

        /// <summary>
        /// Race number within the season/series schedule
        /// </summary>
        /// <value>Race number within the season/series schedule</value>
        [DataMember(Name="race_number", EmitDefaultValue=false)]
        public int? RaceNumber { get; set; }

        /// <summary>
        /// Indicates whether restrictor plates are required for this race
        /// </summary>
        /// <value>Indicates whether restrictor plates are required for this race</value>
        [DataMember(Name="restrictor_plate", EmitDefaultValue=false)]
        public bool? RestrictorPlate { get; set; }

        /// <summary>
        /// String formatted representation of the total time of race HH:MM:SS
        /// </summary>
        /// <value>String formatted representation of the total time of race HH:MM:SS</value>
        [DataMember(Name="total_race_time", EmitDefaultValue=false)]
        public string TotalRaceTime { get; set; }

        /// <summary>
        /// Promoter of the race
        /// </summary>
        /// <value>Promoter of the race</value>
        [DataMember(Name="promoter", EmitDefaultValue=false)]
        public string Promoter { get; set; }

        /// <summary>
        /// Scheduled number of laps for this race
        /// </summary>
        /// <value>Scheduled number of laps for this race</value>
        [DataMember(Name="laps", EmitDefaultValue=false)]
        public int? Laps { get; set; }

        /// <summary>
        /// Actual number of laps for this race
        /// </summary>
        /// <value>Actual number of laps for this race</value>
        [DataMember(Name="actual_laps", EmitDefaultValue=false)]
        public int? ActualLaps { get; set; }

        /// <summary>
        /// Scheduled distance for this race in miles
        /// </summary>
        /// <value>Scheduled distance for this race in miles</value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public double? Distance { get; set; }

        /// <summary>
        /// Actual distance for this race in miles
        /// </summary>
        /// <value>Actual distance for this race in miles</value>
        [DataMember(Name="actual_distance", EmitDefaultValue=false)]
        public double? ActualDistance { get; set; }

        /// <summary>
        /// Indicates whether inspection has been completed
        /// </summary>
        /// <value>Indicates whether inspection has been completed</value>
        [DataMember(Name="inspection_complete", EmitDefaultValue=false)]
        public bool? InspectionComplete { get; set; }

        /// <summary>
        /// Number of cars in this race
        /// </summary>
        /// <value>Number of cars in this race</value>
        [DataMember(Name="number_of_cars_in_field", EmitDefaultValue=false)]
        public int? NumberOfCarsInField { get; set; }

        /// <summary>
        /// API Driver ID for the driver who won the pole for this race
        /// </summary>
        /// <value>API Driver ID for the driver who won the pole for this race</value>
        [DataMember(Name="pole_winner_driver_id", EmitDefaultValue=false)]
        public int? PoleWinnerDriverId { get; set; }

        /// <summary>
        /// Lap speed for the pole winner
        /// </summary>
        /// <value>Lap speed for the pole winner</value>
        [DataMember(Name="pole_winner_speed", EmitDefaultValue=false)]
        public double? PoleWinnerSpeed { get; set; }

        /// <summary>
        /// Number of times the leader changed (Start Finish based) for this race
        /// </summary>
        /// <value>Number of times the leader changed (Start Finish based) for this race</value>
        [DataMember(Name="number_of_lead_changes", EmitDefaultValue=false)]
        public int? NumberOfLeadChanges { get; set; }

        /// <summary>
        /// Number of distinct leaders (Start Finish based) for this race
        /// </summary>
        /// <value>Number of distinct leaders (Start Finish based) for this race</value>
        [DataMember(Name="number_of_leaders", EmitDefaultValue=false)]
        public int? NumberOfLeaders { get; set; }

        /// <summary>
        /// Average speed of this race
        /// </summary>
        /// <value>Average speed of this race</value>
        [DataMember(Name="average_speed", EmitDefaultValue=false)]
        public double? AverageSpeed { get; set; }

        /// <summary>
        /// String representation of the margin of victory.  May be the time between 1st and 2nd place finishers or Caution if the race ended under caution.
        /// </summary>
        /// <value>String representation of the margin of victory.  May be the time between 1st and 2nd place finishers or Caution if the race ended under caution.</value>
        [DataMember(Name="margin_of_victory", EmitDefaultValue=false)]
        public string MarginOfVictory { get; set; }

        /// <summary>
        /// Name of radio broadcaster for this race
        /// </summary>
        /// <value>Name of radio broadcaster for this race</value>
        [DataMember(Name="radio_broadcaster", EmitDefaultValue=false)]
        public string RadioBroadcaster { get; set; }

        /// <summary>
        /// Name of television broadcaster for this race
        /// </summary>
        /// <value>Name of television broadcaster for this race</value>
        [DataMember(Name="television_broadcaster", EmitDefaultValue=false)]
        public string TelevisionBroadcaster { get; set; }

        /// <summary>
        /// Name of satellite radio broadcaster for this race
        /// </summary>
        /// <value>Name of satellite radio broadcaster for this race</value>
        [DataMember(Name="satellite_radio_broadcaster", EmitDefaultValue=false)]
        public string SatelliteRadioBroadcaster { get; set; }

        /// <summary>
        /// Round of the playoffs that this race is a part of, 0 for non-playoff races
        /// </summary>
        /// <value>Round of the playoffs that this race is a part of, 0 for non-playoff races</value>
        [DataMember(Name="playoff_round", EmitDefaultValue=false)]
        public int? PlayoffRound { get; set; }

        /// <summary>
        /// Indicates when run is a qualifying race
        /// </summary>
        /// <value>Indicates when run is a qualifying race</value>
        [DataMember(Name="is_qualifying_race", EmitDefaultValue=false)]
        public bool? IsQualifyingRace { get; set; }

        /// <summary>
        /// Sequence number of qualifying race
        /// </summary>
        /// <value>Sequence number of qualifying race</value>
        [DataMember(Name="qualifying_race_no", EmitDefaultValue=false)]
        public int? QualifyingRaceNo { get; set; }

        /// <summary>
        /// ID of qualifying race
        /// </summary>
        /// <value>ID of qualifying race</value>
        [DataMember(Name="qualifying_race_id", EmitDefaultValue=false)]
        public int? QualifyingRaceId { get; set; }

        /// <summary>
        /// Indicates whether this race has qualifying
        /// </summary>
        /// <value>Indicates whether this race has qualifying</value>
        [DataMember(Name="has_qualifying", EmitDefaultValue=false)]
        public bool? HasQualifying { get; set; }

        /// <summary>
        /// URL to practice results
        /// </summary>
        /// <value>URL to practice results</value>
        [DataMember(Name="practice_results", EmitDefaultValue=false)]
        public string PracticeResults { get; private set; }

        /// <summary>
        /// URL to Qualifying results
        /// </summary>
        /// <value>URL to Qualifying results</value>
        [DataMember(Name="qualifying_results", EmitDefaultValue=false)]
        public string QualifyingResults { get; private set; }

        /// <summary>
        /// URL to race results
        /// </summary>
        /// <value>URL to race results</value>
        [DataMember(Name="race_results", EmitDefaultValue=false)]
        public string RaceResults { get; private set; }

        /// <summary>
        /// URL to race cautions
        /// </summary>
        /// <value>URL to race cautions</value>
        [DataMember(Name="cautions", EmitDefaultValue=false)]
        public string Cautions { get; private set; }

        /// <summary>
        /// URL to race infractions
        /// </summary>
        /// <value>URL to race infractions</value>
        [DataMember(Name="infractions", EmitDefaultValue=false)]
        public string Infractions { get; private set; }

        /// <summary>
        /// URL to race lap leaders
        /// </summary>
        /// <value>URL to race lap leaders</value>
        [DataMember(Name="lap_leaders", EmitDefaultValue=false)]
        public string LapLeaders { get; private set; }

        /// <summary>
        /// URL to race pitstops
        /// </summary>
        /// <value>URL to race pitstops</value>
        [DataMember(Name="pitstops", EmitDefaultValue=false)]
        public string Pitstops { get; private set; }

        /// <summary>
        /// URL to race stages
        /// </summary>
        /// <value>URL to race stages</value>
        [DataMember(Name="stages", EmitDefaultValue=false)]
        public string Stages { get; private set; }

        /// <summary>
        /// Race date
        /// </summary>
        /// <value>Race date</value>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public DateTimeOffset? Date { get; set; }

        /// <summary>
        /// Date qualifying was held for this race
        /// </summary>
        /// <value>Date qualifying was held for this race</value>
        [DataMember(Name="qualifying_date", EmitDefaultValue=false)]
        public DateTimeOffset? QualifyingDate { get; set; }

        /// <summary>
        /// Race comments
        /// </summary>
        /// <value>Race comments</value>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public string Comments { get; set; }

        /// <summary>
        /// Historical track identifier
        /// </summary>
        /// <value>Historical track identifier</value>
        [DataMember(Name="history_track_id", EmitDefaultValue=false)]
        public int? HistoryTrackId { get; set; }

        /// <summary>
        /// Track identifier
        /// </summary>
        /// <value>Track identifier</value>
        [DataMember(Name="track_id", EmitDefaultValue=false)]
        public int? TrackId { get; set; }

        /// <summary>
        /// Gets or Sets FastestLapAward
        /// </summary>
        [DataMember(Name="fastest_lap_award", EmitDefaultValue=false)]
        public FastestLapAwards FastestLapAward { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Race {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PrincipalRaceId: ").Append(PrincipalRaceId).Append("\n");
            sb.Append("  HistoryRaceId: ").Append(HistoryRaceId).Append("\n");
            sb.Append("  RaceweekId: ").Append(RaceweekId).Append("\n");
            sb.Append("  SeriesId: ").Append(SeriesId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RaceTypeId: ").Append(RaceTypeId).Append("\n");
            sb.Append("  RaceNumber: ").Append(RaceNumber).Append("\n");
            sb.Append("  RestrictorPlate: ").Append(RestrictorPlate).Append("\n");
            sb.Append("  TotalRaceTime: ").Append(TotalRaceTime).Append("\n");
            sb.Append("  Promoter: ").Append(Promoter).Append("\n");
            sb.Append("  Laps: ").Append(Laps).Append("\n");
            sb.Append("  ActualLaps: ").Append(ActualLaps).Append("\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  ActualDistance: ").Append(ActualDistance).Append("\n");
            sb.Append("  InspectionComplete: ").Append(InspectionComplete).Append("\n");
            sb.Append("  NumberOfCarsInField: ").Append(NumberOfCarsInField).Append("\n");
            sb.Append("  PoleWinnerDriverId: ").Append(PoleWinnerDriverId).Append("\n");
            sb.Append("  PoleWinnerSpeed: ").Append(PoleWinnerSpeed).Append("\n");
            sb.Append("  NumberOfLeadChanges: ").Append(NumberOfLeadChanges).Append("\n");
            sb.Append("  NumberOfLeaders: ").Append(NumberOfLeaders).Append("\n");
            sb.Append("  AverageSpeed: ").Append(AverageSpeed).Append("\n");
            sb.Append("  MarginOfVictory: ").Append(MarginOfVictory).Append("\n");
            sb.Append("  RadioBroadcaster: ").Append(RadioBroadcaster).Append("\n");
            sb.Append("  TelevisionBroadcaster: ").Append(TelevisionBroadcaster).Append("\n");
            sb.Append("  SatelliteRadioBroadcaster: ").Append(SatelliteRadioBroadcaster).Append("\n");
            sb.Append("  PlayoffRound: ").Append(PlayoffRound).Append("\n");
            sb.Append("  IsQualifyingRace: ").Append(IsQualifyingRace).Append("\n");
            sb.Append("  QualifyingRaceNo: ").Append(QualifyingRaceNo).Append("\n");
            sb.Append("  QualifyingRaceId: ").Append(QualifyingRaceId).Append("\n");
            sb.Append("  HasQualifying: ").Append(HasQualifying).Append("\n");
            sb.Append("  PracticeResults: ").Append(PracticeResults).Append("\n");
            sb.Append("  QualifyingResults: ").Append(QualifyingResults).Append("\n");
            sb.Append("  RaceResults: ").Append(RaceResults).Append("\n");
            sb.Append("  Cautions: ").Append(Cautions).Append("\n");
            sb.Append("  Infractions: ").Append(Infractions).Append("\n");
            sb.Append("  LapLeaders: ").Append(LapLeaders).Append("\n");
            sb.Append("  Pitstops: ").Append(Pitstops).Append("\n");
            sb.Append("  Stages: ").Append(Stages).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  QualifyingDate: ").Append(QualifyingDate).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  HistoryTrackId: ").Append(HistoryTrackId).Append("\n");
            sb.Append("  TrackId: ").Append(TrackId).Append("\n");
            sb.Append("  FastestLapAward: ").Append(FastestLapAward).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Race);
        }

        /// <summary>
        /// Returns true if Race instances are equal
        /// </summary>
        /// <param name="input">Instance of Race to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Race input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.PrincipalRaceId == input.PrincipalRaceId ||
                    (this.PrincipalRaceId != null &&
                    this.PrincipalRaceId.Equals(input.PrincipalRaceId))
                ) && 
                (
                    this.HistoryRaceId == input.HistoryRaceId ||
                    (this.HistoryRaceId != null &&
                    this.HistoryRaceId.Equals(input.HistoryRaceId))
                ) && 
                (
                    this.RaceweekId == input.RaceweekId ||
                    (this.RaceweekId != null &&
                    this.RaceweekId.Equals(input.RaceweekId))
                ) && 
                (
                    this.SeriesId == input.SeriesId ||
                    (this.SeriesId != null &&
                    this.SeriesId.Equals(input.SeriesId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.RaceTypeId == input.RaceTypeId ||
                    (this.RaceTypeId != null &&
                    this.RaceTypeId.Equals(input.RaceTypeId))
                ) && 
                (
                    this.RaceNumber == input.RaceNumber ||
                    (this.RaceNumber != null &&
                    this.RaceNumber.Equals(input.RaceNumber))
                ) && 
                (
                    this.RestrictorPlate == input.RestrictorPlate ||
                    (this.RestrictorPlate != null &&
                    this.RestrictorPlate.Equals(input.RestrictorPlate))
                ) && 
                (
                    this.TotalRaceTime == input.TotalRaceTime ||
                    (this.TotalRaceTime != null &&
                    this.TotalRaceTime.Equals(input.TotalRaceTime))
                ) && 
                (
                    this.Promoter == input.Promoter ||
                    (this.Promoter != null &&
                    this.Promoter.Equals(input.Promoter))
                ) && 
                (
                    this.Laps == input.Laps ||
                    (this.Laps != null &&
                    this.Laps.Equals(input.Laps))
                ) && 
                (
                    this.ActualLaps == input.ActualLaps ||
                    (this.ActualLaps != null &&
                    this.ActualLaps.Equals(input.ActualLaps))
                ) && 
                (
                    this.Distance == input.Distance ||
                    (this.Distance != null &&
                    this.Distance.Equals(input.Distance))
                ) && 
                (
                    this.ActualDistance == input.ActualDistance ||
                    (this.ActualDistance != null &&
                    this.ActualDistance.Equals(input.ActualDistance))
                ) && 
                (
                    this.InspectionComplete == input.InspectionComplete ||
                    (this.InspectionComplete != null &&
                    this.InspectionComplete.Equals(input.InspectionComplete))
                ) && 
                (
                    this.NumberOfCarsInField == input.NumberOfCarsInField ||
                    (this.NumberOfCarsInField != null &&
                    this.NumberOfCarsInField.Equals(input.NumberOfCarsInField))
                ) && 
                (
                    this.PoleWinnerDriverId == input.PoleWinnerDriverId ||
                    (this.PoleWinnerDriverId != null &&
                    this.PoleWinnerDriverId.Equals(input.PoleWinnerDriverId))
                ) && 
                (
                    this.PoleWinnerSpeed == input.PoleWinnerSpeed ||
                    (this.PoleWinnerSpeed != null &&
                    this.PoleWinnerSpeed.Equals(input.PoleWinnerSpeed))
                ) && 
                (
                    this.NumberOfLeadChanges == input.NumberOfLeadChanges ||
                    (this.NumberOfLeadChanges != null &&
                    this.NumberOfLeadChanges.Equals(input.NumberOfLeadChanges))
                ) && 
                (
                    this.NumberOfLeaders == input.NumberOfLeaders ||
                    (this.NumberOfLeaders != null &&
                    this.NumberOfLeaders.Equals(input.NumberOfLeaders))
                ) && 
                (
                    this.AverageSpeed == input.AverageSpeed ||
                    (this.AverageSpeed != null &&
                    this.AverageSpeed.Equals(input.AverageSpeed))
                ) && 
                (
                    this.MarginOfVictory == input.MarginOfVictory ||
                    (this.MarginOfVictory != null &&
                    this.MarginOfVictory.Equals(input.MarginOfVictory))
                ) && 
                (
                    this.RadioBroadcaster == input.RadioBroadcaster ||
                    (this.RadioBroadcaster != null &&
                    this.RadioBroadcaster.Equals(input.RadioBroadcaster))
                ) && 
                (
                    this.TelevisionBroadcaster == input.TelevisionBroadcaster ||
                    (this.TelevisionBroadcaster != null &&
                    this.TelevisionBroadcaster.Equals(input.TelevisionBroadcaster))
                ) && 
                (
                    this.SatelliteRadioBroadcaster == input.SatelliteRadioBroadcaster ||
                    (this.SatelliteRadioBroadcaster != null &&
                    this.SatelliteRadioBroadcaster.Equals(input.SatelliteRadioBroadcaster))
                ) && 
                (
                    this.PlayoffRound == input.PlayoffRound ||
                    (this.PlayoffRound != null &&
                    this.PlayoffRound.Equals(input.PlayoffRound))
                ) && 
                (
                    this.IsQualifyingRace == input.IsQualifyingRace ||
                    (this.IsQualifyingRace != null &&
                    this.IsQualifyingRace.Equals(input.IsQualifyingRace))
                ) && 
                (
                    this.QualifyingRaceNo == input.QualifyingRaceNo ||
                    (this.QualifyingRaceNo != null &&
                    this.QualifyingRaceNo.Equals(input.QualifyingRaceNo))
                ) && 
                (
                    this.QualifyingRaceId == input.QualifyingRaceId ||
                    (this.QualifyingRaceId != null &&
                    this.QualifyingRaceId.Equals(input.QualifyingRaceId))
                ) && 
                (
                    this.HasQualifying == input.HasQualifying ||
                    (this.HasQualifying != null &&
                    this.HasQualifying.Equals(input.HasQualifying))
                ) && 
                (
                    this.PracticeResults == input.PracticeResults ||
                    (this.PracticeResults != null &&
                    this.PracticeResults.Equals(input.PracticeResults))
                ) && 
                (
                    this.QualifyingResults == input.QualifyingResults ||
                    (this.QualifyingResults != null &&
                    this.QualifyingResults.Equals(input.QualifyingResults))
                ) && 
                (
                    this.RaceResults == input.RaceResults ||
                    (this.RaceResults != null &&
                    this.RaceResults.Equals(input.RaceResults))
                ) && 
                (
                    this.Cautions == input.Cautions ||
                    (this.Cautions != null &&
                    this.Cautions.Equals(input.Cautions))
                ) && 
                (
                    this.Infractions == input.Infractions ||
                    (this.Infractions != null &&
                    this.Infractions.Equals(input.Infractions))
                ) && 
                (
                    this.LapLeaders == input.LapLeaders ||
                    (this.LapLeaders != null &&
                    this.LapLeaders.Equals(input.LapLeaders))
                ) && 
                (
                    this.Pitstops == input.Pitstops ||
                    (this.Pitstops != null &&
                    this.Pitstops.Equals(input.Pitstops))
                ) && 
                (
                    this.Stages == input.Stages ||
                    (this.Stages != null &&
                    this.Stages.Equals(input.Stages))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.QualifyingDate == input.QualifyingDate ||
                    (this.QualifyingDate != null &&
                    this.QualifyingDate.Equals(input.QualifyingDate))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.HistoryTrackId == input.HistoryTrackId ||
                    (this.HistoryTrackId != null &&
                    this.HistoryTrackId.Equals(input.HistoryTrackId))
                ) && 
                (
                    this.TrackId == input.TrackId ||
                    (this.TrackId != null &&
                    this.TrackId.Equals(input.TrackId))
                ) && 
                (
                    this.FastestLapAward == input.FastestLapAward ||
                    (this.FastestLapAward != null &&
                    this.FastestLapAward.Equals(input.FastestLapAward))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.PrincipalRaceId != null)
                    hashCode = hashCode * 59 + this.PrincipalRaceId.GetHashCode();
                if (this.HistoryRaceId != null)
                    hashCode = hashCode * 59 + this.HistoryRaceId.GetHashCode();
                if (this.RaceweekId != null)
                    hashCode = hashCode * 59 + this.RaceweekId.GetHashCode();
                if (this.SeriesId != null)
                    hashCode = hashCode * 59 + this.SeriesId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.RaceTypeId != null)
                    hashCode = hashCode * 59 + this.RaceTypeId.GetHashCode();
                if (this.RaceNumber != null)
                    hashCode = hashCode * 59 + this.RaceNumber.GetHashCode();
                if (this.RestrictorPlate != null)
                    hashCode = hashCode * 59 + this.RestrictorPlate.GetHashCode();
                if (this.TotalRaceTime != null)
                    hashCode = hashCode * 59 + this.TotalRaceTime.GetHashCode();
                if (this.Promoter != null)
                    hashCode = hashCode * 59 + this.Promoter.GetHashCode();
                if (this.Laps != null)
                    hashCode = hashCode * 59 + this.Laps.GetHashCode();
                if (this.ActualLaps != null)
                    hashCode = hashCode * 59 + this.ActualLaps.GetHashCode();
                if (this.Distance != null)
                    hashCode = hashCode * 59 + this.Distance.GetHashCode();
                if (this.ActualDistance != null)
                    hashCode = hashCode * 59 + this.ActualDistance.GetHashCode();
                if (this.InspectionComplete != null)
                    hashCode = hashCode * 59 + this.InspectionComplete.GetHashCode();
                if (this.NumberOfCarsInField != null)
                    hashCode = hashCode * 59 + this.NumberOfCarsInField.GetHashCode();
                if (this.PoleWinnerDriverId != null)
                    hashCode = hashCode * 59 + this.PoleWinnerDriverId.GetHashCode();
                if (this.PoleWinnerSpeed != null)
                    hashCode = hashCode * 59 + this.PoleWinnerSpeed.GetHashCode();
                if (this.NumberOfLeadChanges != null)
                    hashCode = hashCode * 59 + this.NumberOfLeadChanges.GetHashCode();
                if (this.NumberOfLeaders != null)
                    hashCode = hashCode * 59 + this.NumberOfLeaders.GetHashCode();
                if (this.AverageSpeed != null)
                    hashCode = hashCode * 59 + this.AverageSpeed.GetHashCode();
                if (this.MarginOfVictory != null)
                    hashCode = hashCode * 59 + this.MarginOfVictory.GetHashCode();
                if (this.RadioBroadcaster != null)
                    hashCode = hashCode * 59 + this.RadioBroadcaster.GetHashCode();
                if (this.TelevisionBroadcaster != null)
                    hashCode = hashCode * 59 + this.TelevisionBroadcaster.GetHashCode();
                if (this.SatelliteRadioBroadcaster != null)
                    hashCode = hashCode * 59 + this.SatelliteRadioBroadcaster.GetHashCode();
                if (this.PlayoffRound != null)
                    hashCode = hashCode * 59 + this.PlayoffRound.GetHashCode();
                if (this.IsQualifyingRace != null)
                    hashCode = hashCode * 59 + this.IsQualifyingRace.GetHashCode();
                if (this.QualifyingRaceNo != null)
                    hashCode = hashCode * 59 + this.QualifyingRaceNo.GetHashCode();
                if (this.QualifyingRaceId != null)
                    hashCode = hashCode * 59 + this.QualifyingRaceId.GetHashCode();
                if (this.HasQualifying != null)
                    hashCode = hashCode * 59 + this.HasQualifying.GetHashCode();
                if (this.PracticeResults != null)
                    hashCode = hashCode * 59 + this.PracticeResults.GetHashCode();
                if (this.QualifyingResults != null)
                    hashCode = hashCode * 59 + this.QualifyingResults.GetHashCode();
                if (this.RaceResults != null)
                    hashCode = hashCode * 59 + this.RaceResults.GetHashCode();
                if (this.Cautions != null)
                    hashCode = hashCode * 59 + this.Cautions.GetHashCode();
                if (this.Infractions != null)
                    hashCode = hashCode * 59 + this.Infractions.GetHashCode();
                if (this.LapLeaders != null)
                    hashCode = hashCode * 59 + this.LapLeaders.GetHashCode();
                if (this.Pitstops != null)
                    hashCode = hashCode * 59 + this.Pitstops.GetHashCode();
                if (this.Stages != null)
                    hashCode = hashCode * 59 + this.Stages.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.QualifyingDate != null)
                    hashCode = hashCode * 59 + this.QualifyingDate.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.HistoryTrackId != null)
                    hashCode = hashCode * 59 + this.HistoryTrackId.GetHashCode();
                if (this.TrackId != null)
                    hashCode = hashCode * 59 + this.TrackId.GetHashCode();
                if (this.FastestLapAward != null)
                    hashCode = hashCode * 59 + this.FastestLapAward.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
