/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// ScheduledActionSchedule
    /// </summary>
    [DataContract]
        public partial class ScheduledActionSchedule :  IEquatable<ScheduledActionSchedule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledActionSchedule" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="trackingId">trackingId.</param>
        /// <param name="scheduledActionId">scheduledActionId.</param>
        /// <param name="value">value.</param>
        /// <param name="intervalInSeconds">intervalInSeconds (required).</param>
        /// <param name="runOrder">runOrder.</param>
        /// <param name="lastRun">lastRun.</param>
        /// <param name="isActive">isActive (default to true).</param>
        /// <param name="actionDetailId">actionDetailId.</param>
        /// <param name="description">description.</param>
        public ScheduledActionSchedule(int? id = default(int?), Guid? trackingId = default(Guid?), int? scheduledActionId = default(int?), int? value = default(int?), int? intervalInSeconds = default(int?), int? runOrder = default(int?), DateTimeOffset? lastRun = default(DateTimeOffset?), bool? isActive = true, int? actionDetailId = default(int?), string description = default(string))
        {
            // to ensure "intervalInSeconds" is required (not null)
            if (intervalInSeconds == null)
            {
                throw new InvalidDataException("intervalInSeconds is a required property for ScheduledActionSchedule and cannot be null");
            }
            else
            {
                this.IntervalInSeconds = intervalInSeconds;
            }
            this.Id = id;
            this.TrackingId = trackingId;
            this.ScheduledActionId = scheduledActionId;
            this.Value = value;
            this.RunOrder = runOrder;
            this.LastRun = lastRun;
            // use default value if no "isActive" provided
            if (isActive == null)
            {
                this.IsActive = true;
            }
            else
            {
                this.IsActive = isActive;
            }
            this.ActionDetailId = actionDetailId;
            this.Description = description;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets TrackingId
        /// </summary>
        [DataMember(Name="tracking_id", EmitDefaultValue=false)]
        public Guid? TrackingId { get; set; }

        /// <summary>
        /// Gets or Sets ScheduledActionId
        /// </summary>
        [DataMember(Name="ScheduledActionId", EmitDefaultValue=false)]
        public int? ScheduledActionId { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="Value", EmitDefaultValue=false)]
        public int? Value { get; set; }

        /// <summary>
        /// Gets or Sets IntervalInSeconds
        /// </summary>
        [DataMember(Name="IntervalInSeconds", EmitDefaultValue=false)]
        public int? IntervalInSeconds { get; set; }

        /// <summary>
        /// Gets or Sets RunOrder
        /// </summary>
        [DataMember(Name="RunOrder", EmitDefaultValue=false)]
        public int? RunOrder { get; set; }

        /// <summary>
        /// Gets or Sets LastRun
        /// </summary>
        [DataMember(Name="LastRun", EmitDefaultValue=false)]
        public DateTimeOffset? LastRun { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name="IsActive", EmitDefaultValue=false)]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Gets or Sets ActionDetailId
        /// </summary>
        [DataMember(Name="ActionDetailId", EmitDefaultValue=false)]
        public int? ActionDetailId { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScheduledActionSchedule {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TrackingId: ").Append(TrackingId).Append("\n");
            sb.Append("  ScheduledActionId: ").Append(ScheduledActionId).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  IntervalInSeconds: ").Append(IntervalInSeconds).Append("\n");
            sb.Append("  RunOrder: ").Append(RunOrder).Append("\n");
            sb.Append("  LastRun: ").Append(LastRun).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ActionDetailId: ").Append(ActionDetailId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduledActionSchedule);
        }

        /// <summary>
        /// Returns true if ScheduledActionSchedule instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduledActionSchedule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduledActionSchedule input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.TrackingId == input.TrackingId ||
                    (this.TrackingId != null &&
                    this.TrackingId.Equals(input.TrackingId))
                ) && 
                (
                    this.ScheduledActionId == input.ScheduledActionId ||
                    (this.ScheduledActionId != null &&
                    this.ScheduledActionId.Equals(input.ScheduledActionId))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.IntervalInSeconds == input.IntervalInSeconds ||
                    (this.IntervalInSeconds != null &&
                    this.IntervalInSeconds.Equals(input.IntervalInSeconds))
                ) && 
                (
                    this.RunOrder == input.RunOrder ||
                    (this.RunOrder != null &&
                    this.RunOrder.Equals(input.RunOrder))
                ) && 
                (
                    this.LastRun == input.LastRun ||
                    (this.LastRun != null &&
                    this.LastRun.Equals(input.LastRun))
                ) && 
                (
                    this.IsActive == input.IsActive ||
                    (this.IsActive != null &&
                    this.IsActive.Equals(input.IsActive))
                ) && 
                (
                    this.ActionDetailId == input.ActionDetailId ||
                    (this.ActionDetailId != null &&
                    this.ActionDetailId.Equals(input.ActionDetailId))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.TrackingId != null)
                    hashCode = hashCode * 59 + this.TrackingId.GetHashCode();
                if (this.ScheduledActionId != null)
                    hashCode = hashCode * 59 + this.ScheduledActionId.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.IntervalInSeconds != null)
                    hashCode = hashCode * 59 + this.IntervalInSeconds.GetHashCode();
                if (this.RunOrder != null)
                    hashCode = hashCode * 59 + this.RunOrder.GetHashCode();
                if (this.LastRun != null)
                    hashCode = hashCode * 59 + this.LastRun.GetHashCode();
                if (this.IsActive != null)
                    hashCode = hashCode * 59 + this.IsActive.GetHashCode();
                if (this.ActionDetailId != null)
                    hashCode = hashCode * 59 + this.ActionDetailId.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
