/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Track
    /// </summary>
    [DataContract]
        public partial class Track :  IEquatable<Track>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Track" /> class.
        /// </summary>
        /// <param name="id">Unique identifier given and used by the NASCAR Data API.</param>
        /// <param name="historyTrackId">History track id.</param>
        /// <param name="nascaroneTrackId">nascaroneTrackId.</param>
        /// <param name="name">The name of the track.</param>
        /// <param name="owner">The owner of the track.</param>
        /// <param name="sponsorName">The name of the track sponsor.</param>
        /// <param name="surface">The type of track surface.</param>
        /// <param name="type">The type of track.</param>
        /// <param name="banking">Track banking.</param>
        /// <param name="description">Description of the track.</param>
        /// <param name="city">The city where the track is located.</param>
        /// <param name="state">The state where the track is located.</param>
        /// <param name="frontstretchLength">The length of the track&#x27;s frontstretch in miles.</param>
        /// <param name="backstretchLength">The length of the track&#x27;s backstretch in miles.</param>
        /// <param name="yearBuilt">The year the track was built.</param>
        /// <param name="length">The track&#x27;s total length in miles.</param>
        /// <param name="cautionCarSpeed">The track&#x27;s caution speed.</param>
        /// <param name="logo">The URL of the track logo.</param>
        public Track(int? id = default(int?), int? historyTrackId = default(int?), int? nascaroneTrackId = default(int?), string name = default(string), string owner = default(string), string sponsorName = default(string), string surface = default(string), string type = default(string), string banking = default(string), string description = default(string), string city = default(string), string state = default(string), int? frontstretchLength = default(int?), int? backstretchLength = default(int?), int? yearBuilt = default(int?), double? length = default(double?), int? cautionCarSpeed = default(int?), string logo = default(string))
        {
            this.Id = id;
            this.HistoryTrackId = historyTrackId;
            this.NascaroneTrackId = nascaroneTrackId;
            this.Name = name;
            this.Owner = owner;
            this.SponsorName = sponsorName;
            this.Surface = surface;
            this.Type = type;
            this.Banking = banking;
            this.Description = description;
            this.City = city;
            this.State = state;
            this.FrontstretchLength = frontstretchLength;
            this.BackstretchLength = backstretchLength;
            this.YearBuilt = yearBuilt;
            this.Length = length;
            this.CautionCarSpeed = cautionCarSpeed;
            this.Logo = logo;
        }
        
        /// <summary>
        /// Unique identifier given and used by the NASCAR Data API
        /// </summary>
        /// <value>Unique identifier given and used by the NASCAR Data API</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// History track id
        /// </summary>
        /// <value>History track id</value>
        [DataMember(Name="history_track_id", EmitDefaultValue=false)]
        public int? HistoryTrackId { get; set; }

        /// <summary>
        /// Gets or Sets NascaroneTrackId
        /// </summary>
        [DataMember(Name="nascarone_track_id", EmitDefaultValue=false)]
        public int? NascaroneTrackId { get; set; }

        /// <summary>
        /// The name of the track
        /// </summary>
        /// <value>The name of the track</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The owner of the track
        /// </summary>
        /// <value>The owner of the track</value>
        [DataMember(Name="owner", EmitDefaultValue=false)]
        public string Owner { get; set; }

        /// <summary>
        /// The name of the track sponsor
        /// </summary>
        /// <value>The name of the track sponsor</value>
        [DataMember(Name="sponsor_name", EmitDefaultValue=false)]
        public string SponsorName { get; set; }

        /// <summary>
        /// The type of track surface
        /// </summary>
        /// <value>The type of track surface</value>
        [DataMember(Name="surface", EmitDefaultValue=false)]
        public string Surface { get; set; }

        /// <summary>
        /// The type of track
        /// </summary>
        /// <value>The type of track</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Track banking
        /// </summary>
        /// <value>Track banking</value>
        [DataMember(Name="banking", EmitDefaultValue=false)]
        public string Banking { get; set; }

        /// <summary>
        /// Description of the track
        /// </summary>
        /// <value>Description of the track</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// The city where the track is located
        /// </summary>
        /// <value>The city where the track is located</value>
        [DataMember(Name="city", EmitDefaultValue=false)]
        public string City { get; set; }

        /// <summary>
        /// The state where the track is located
        /// </summary>
        /// <value>The state where the track is located</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// The length of the track&#x27;s frontstretch in miles
        /// </summary>
        /// <value>The length of the track&#x27;s frontstretch in miles</value>
        [DataMember(Name="frontstretch_length", EmitDefaultValue=false)]
        public int? FrontstretchLength { get; set; }

        /// <summary>
        /// The length of the track&#x27;s backstretch in miles
        /// </summary>
        /// <value>The length of the track&#x27;s backstretch in miles</value>
        [DataMember(Name="backstretch_length", EmitDefaultValue=false)]
        public int? BackstretchLength { get; set; }

        /// <summary>
        /// The year the track was built
        /// </summary>
        /// <value>The year the track was built</value>
        [DataMember(Name="year_built", EmitDefaultValue=false)]
        public int? YearBuilt { get; set; }

        /// <summary>
        /// The track&#x27;s total length in miles
        /// </summary>
        /// <value>The track&#x27;s total length in miles</value>
        [DataMember(Name="length", EmitDefaultValue=false)]
        public double? Length { get; set; }

        /// <summary>
        /// The track&#x27;s caution speed
        /// </summary>
        /// <value>The track&#x27;s caution speed</value>
        [DataMember(Name="caution_car_speed", EmitDefaultValue=false)]
        public int? CautionCarSpeed { get; set; }

        /// <summary>
        /// The URL of the track logo
        /// </summary>
        /// <value>The URL of the track logo</value>
        [DataMember(Name="logo", EmitDefaultValue=false)]
        public string Logo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Track {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  HistoryTrackId: ").Append(HistoryTrackId).Append("\n");
            sb.Append("  NascaroneTrackId: ").Append(NascaroneTrackId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  SponsorName: ").Append(SponsorName).Append("\n");
            sb.Append("  Surface: ").Append(Surface).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Banking: ").Append(Banking).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  FrontstretchLength: ").Append(FrontstretchLength).Append("\n");
            sb.Append("  BackstretchLength: ").Append(BackstretchLength).Append("\n");
            sb.Append("  YearBuilt: ").Append(YearBuilt).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  CautionCarSpeed: ").Append(CautionCarSpeed).Append("\n");
            sb.Append("  Logo: ").Append(Logo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Track);
        }

        /// <summary>
        /// Returns true if Track instances are equal
        /// </summary>
        /// <param name="input">Instance of Track to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Track input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.HistoryTrackId == input.HistoryTrackId ||
                    (this.HistoryTrackId != null &&
                    this.HistoryTrackId.Equals(input.HistoryTrackId))
                ) && 
                (
                    this.NascaroneTrackId == input.NascaroneTrackId ||
                    (this.NascaroneTrackId != null &&
                    this.NascaroneTrackId.Equals(input.NascaroneTrackId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Owner == input.Owner ||
                    (this.Owner != null &&
                    this.Owner.Equals(input.Owner))
                ) && 
                (
                    this.SponsorName == input.SponsorName ||
                    (this.SponsorName != null &&
                    this.SponsorName.Equals(input.SponsorName))
                ) && 
                (
                    this.Surface == input.Surface ||
                    (this.Surface != null &&
                    this.Surface.Equals(input.Surface))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Banking == input.Banking ||
                    (this.Banking != null &&
                    this.Banking.Equals(input.Banking))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.City == input.City ||
                    (this.City != null &&
                    this.City.Equals(input.City))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.FrontstretchLength == input.FrontstretchLength ||
                    (this.FrontstretchLength != null &&
                    this.FrontstretchLength.Equals(input.FrontstretchLength))
                ) && 
                (
                    this.BackstretchLength == input.BackstretchLength ||
                    (this.BackstretchLength != null &&
                    this.BackstretchLength.Equals(input.BackstretchLength))
                ) && 
                (
                    this.YearBuilt == input.YearBuilt ||
                    (this.YearBuilt != null &&
                    this.YearBuilt.Equals(input.YearBuilt))
                ) && 
                (
                    this.Length == input.Length ||
                    (this.Length != null &&
                    this.Length.Equals(input.Length))
                ) && 
                (
                    this.CautionCarSpeed == input.CautionCarSpeed ||
                    (this.CautionCarSpeed != null &&
                    this.CautionCarSpeed.Equals(input.CautionCarSpeed))
                ) && 
                (
                    this.Logo == input.Logo ||
                    (this.Logo != null &&
                    this.Logo.Equals(input.Logo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.HistoryTrackId != null)
                    hashCode = hashCode * 59 + this.HistoryTrackId.GetHashCode();
                if (this.NascaroneTrackId != null)
                    hashCode = hashCode * 59 + this.NascaroneTrackId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Owner != null)
                    hashCode = hashCode * 59 + this.Owner.GetHashCode();
                if (this.SponsorName != null)
                    hashCode = hashCode * 59 + this.SponsorName.GetHashCode();
                if (this.Surface != null)
                    hashCode = hashCode * 59 + this.Surface.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Banking != null)
                    hashCode = hashCode * 59 + this.Banking.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.City != null)
                    hashCode = hashCode * 59 + this.City.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.FrontstretchLength != null)
                    hashCode = hashCode * 59 + this.FrontstretchLength.GetHashCode();
                if (this.BackstretchLength != null)
                    hashCode = hashCode * 59 + this.BackstretchLength.GetHashCode();
                if (this.YearBuilt != null)
                    hashCode = hashCode * 59 + this.YearBuilt.GetHashCode();
                if (this.Length != null)
                    hashCode = hashCode * 59 + this.Length.GetHashCode();
                if (this.CautionCarSpeed != null)
                    hashCode = hashCode * 59 + this.CautionCarSpeed.GetHashCode();
                if (this.Logo != null)
                    hashCode = hashCode * 59 + this.Logo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
