/* 
 * NASCAR.Data.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = NASCAR.Data.Client.Client.SwaggerDateConverter;

namespace NASCAR.Data.Client.Model
{
    /// <summary>
    /// Represents the account identifiers used in a Wicket request
    /// </summary>
    [DataContract]
        public partial class WicketAccountIds :  IEquatable<WicketAccountIds>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WicketAccountIds" /> class.
        /// </summary>
        /// <param name="gAP">GAP account identifier.</param>
        /// <param name="nDL">NDL account identifier.</param>
        public WicketAccountIds(string gAP = default(string), string nDL = default(string))
        {
            this.GAP = gAP;
            this.NDL = nDL;
        }
        
        /// <summary>
        /// GAP account identifier
        /// </summary>
        /// <value>GAP account identifier</value>
        [DataMember(Name="GAP", EmitDefaultValue=false)]
        public string GAP { get; set; }

        /// <summary>
        /// NDL account identifier
        /// </summary>
        /// <value>NDL account identifier</value>
        [DataMember(Name="NDL", EmitDefaultValue=false)]
        public string NDL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WicketAccountIds {\n");
            sb.Append("  GAP: ").Append(GAP).Append("\n");
            sb.Append("  NDL: ").Append(NDL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WicketAccountIds);
        }

        /// <summary>
        /// Returns true if WicketAccountIds instances are equal
        /// </summary>
        /// <param name="input">Instance of WicketAccountIds to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WicketAccountIds input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GAP == input.GAP ||
                    (this.GAP != null &&
                    this.GAP.Equals(input.GAP))
                ) && 
                (
                    this.NDL == input.NDL ||
                    (this.NDL != null &&
                    this.NDL.Equals(input.NDL))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GAP != null)
                    hashCode = hashCode * 59 + this.GAP.GetHashCode();
                if (this.NDL != null)
                    hashCode = hashCode * 59 + this.NDL.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
