/* 
 * NASCAR Data API
 *
 * Current & Preview API behavior.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using NASCAR.Data.Client.Client;
using NASCAR.Data.Client.Model;

namespace NASCAR.Data.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IStatsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Collection&lt;LoopStat&gt;</returns>
        Collection<LoopStat> StatsLoopStatsGet (int? raceId = null);

        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>ApiResponse of Collection&lt;LoopStat&gt;</returns>
        ApiResponse<Collection<LoopStat>> StatsLoopStatsGetWithHttpInfo (int? raceId = null);
        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>byte[]</returns>
        byte[] StatsReportGet (string key = null);

        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> StatsReportGetWithHttpInfo (string key = null);
        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>AvailableReports</returns>
        AvailableReports StatsReportsGet (int? raceId = null);

        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>ApiResponse of AvailableReports</returns>
        ApiResponse<AvailableReports> StatsReportsGetWithHttpInfo (int? raceId = null);
        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>Collection&lt;SeasonStat&gt;</returns>
        Collection<SeasonStat> StatsSeasonGet (int? seriesId = null, int? season = null);

        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>ApiResponse of Collection&lt;SeasonStat&gt;</returns>
        ApiResponse<Collection<SeasonStat>> StatsSeasonGetWithHttpInfo (int? seriesId = null, int? season = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of Collection&lt;LoopStat&gt;</returns>
        System.Threading.Tasks.Task<Collection<LoopStat>> StatsLoopStatsGetAsync (int? raceId = null);

        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of ApiResponse (Collection&lt;LoopStat&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Collection<LoopStat>>> StatsLoopStatsGetAsyncWithHttpInfo (int? raceId = null);
        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> StatsReportGetAsync (string key = null);

        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> StatsReportGetAsyncWithHttpInfo (string key = null);
        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of AvailableReports</returns>
        System.Threading.Tasks.Task<AvailableReports> StatsReportsGetAsync (int? raceId = null);

        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of ApiResponse (AvailableReports)</returns>
        System.Threading.Tasks.Task<ApiResponse<AvailableReports>> StatsReportsGetAsyncWithHttpInfo (int? raceId = null);
        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>Task of Collection&lt;SeasonStat&gt;</returns>
        System.Threading.Tasks.Task<Collection<SeasonStat>> StatsSeasonGetAsync (int? seriesId = null, int? season = null);

        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>Task of ApiResponse (Collection&lt;SeasonStat&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Collection<SeasonStat>>> StatsSeasonGetAsyncWithHttpInfo (int? seriesId = null, int? season = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class StatsApi : IStatsApi
    {
        private NASCAR.Data.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StatsApi(String basePath)
        {
            this.Configuration = new NASCAR.Data.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = NASCAR.Data.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class
        /// </summary>
        /// <returns></returns>
        public StatsApi()
        {
            this.Configuration = NASCAR.Data.Client.Client.Configuration.Default;

            ExceptionFactory = NASCAR.Data.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StatsApi(NASCAR.Data.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = NASCAR.Data.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = NASCAR.Data.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public NASCAR.Data.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public NASCAR.Data.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Collection&lt;LoopStat&gt;</returns>
        public Collection<LoopStat> StatsLoopStatsGet (int? raceId = null)
        {
             ApiResponse<Collection<LoopStat>> localVarResponse = StatsLoopStatsGetWithHttpInfo(raceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>ApiResponse of Collection&lt;LoopStat&gt;</returns>
        public ApiResponse< Collection<LoopStat> > StatsLoopStatsGetWithHttpInfo (int? raceId = null)
        {

            var localVarPath = "/stats/loop-stats";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (raceId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "race_id", raceId)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsLoopStatsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Collection<LoopStat>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Collection<LoopStat>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Collection<LoopStat>)));
        }

        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of Collection&lt;LoopStat&gt;</returns>
        public async System.Threading.Tasks.Task<Collection<LoopStat>> StatsLoopStatsGetAsync (int? raceId = null)
        {
             ApiResponse<Collection<LoopStat>> localVarResponse = await StatsLoopStatsGetAsyncWithHttpInfo(raceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a list of driver loop statistics for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of ApiResponse (Collection&lt;LoopStat&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Collection<LoopStat>>> StatsLoopStatsGetAsyncWithHttpInfo (int? raceId = null)
        {

            var localVarPath = "/stats/loop-stats";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (raceId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "race_id", raceId)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsLoopStatsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Collection<LoopStat>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Collection<LoopStat>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Collection<LoopStat>)));
        }

        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] StatsReportGet (string key = null)
        {
             ApiResponse<byte[]> localVarResponse = StatsReportGetWithHttpInfo(key);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > StatsReportGetWithHttpInfo (string key = null)
        {

            var localVarPath = "/stats/report";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (key != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "key", key)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsReportGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> StatsReportGetAsync (string key = null)
        {
             ApiResponse<byte[]> localVarResponse = await StatsReportGetAsyncWithHttpInfo(key);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a specific statistical report file for a given key, which typically corresponds to a report path or identifier returned by /reports. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="key">The key or identifier of the statistical report. (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> StatsReportGetAsyncWithHttpInfo (string key = null)
        {

            var localVarPath = "/stats/report";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (key != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "key", key)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsReportGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>AvailableReports</returns>
        public AvailableReports StatsReportsGet (int? raceId = null)
        {
             ApiResponse<AvailableReports> localVarResponse = StatsReportsGetWithHttpInfo(raceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>ApiResponse of AvailableReports</returns>
        public ApiResponse< AvailableReports > StatsReportsGetWithHttpInfo (int? raceId = null)
        {

            var localVarPath = "/stats/reports";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (raceId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "race_id", raceId)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsReportsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AvailableReports>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AvailableReports) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AvailableReports)));
        }

        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of AvailableReports</returns>
        public async System.Threading.Tasks.Task<AvailableReports> StatsReportsGetAsync (int? raceId = null)
        {
             ApiResponse<AvailableReports> localVarResponse = await StatsReportsGetAsyncWithHttpInfo(raceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a list of available statistical report paths for a given race. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="raceId">The unique identifier of the race. (optional)</param>
        /// <returns>Task of ApiResponse (AvailableReports)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AvailableReports>> StatsReportsGetAsyncWithHttpInfo (int? raceId = null)
        {

            var localVarPath = "/stats/reports";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (raceId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "race_id", raceId)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsReportsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AvailableReports>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AvailableReports) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AvailableReports)));
        }

        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>Collection&lt;SeasonStat&gt;</returns>
        public Collection<SeasonStat> StatsSeasonGet (int? seriesId = null, int? season = null)
        {
             ApiResponse<Collection<SeasonStat>> localVarResponse = StatsSeasonGetWithHttpInfo(seriesId, season);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>ApiResponse of Collection&lt;SeasonStat&gt;</returns>
        public ApiResponse< Collection<SeasonStat> > StatsSeasonGetWithHttpInfo (int? seriesId = null, int? season = null)
        {

            var localVarPath = "/stats/season";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (seriesId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "seriesId", seriesId)); // query parameter
            if (season != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "season", season)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsSeasonGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Collection<SeasonStat>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Collection<SeasonStat>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Collection<SeasonStat>)));
        }

        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>Task of Collection&lt;SeasonStat&gt;</returns>
        public async System.Threading.Tasks.Task<Collection<SeasonStat>> StatsSeasonGetAsync (int? seriesId = null, int? season = null)
        {
             ApiResponse<Collection<SeasonStat>> localVarResponse = await StatsSeasonGetAsyncWithHttpInfo(seriesId, season);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a list of driver season statistics for a given series and season. 
        /// </summary>
        /// <exception cref="NASCAR.Data.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="seriesId">The unique identifier of the series. (optional)</param>
        /// <param name="season">The season for which to retrieve statistics. (optional)</param>
        /// <returns>Task of ApiResponse (Collection&lt;SeasonStat&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Collection<SeasonStat>>> StatsSeasonGetAsyncWithHttpInfo (int? seriesId = null, int? season = null)
        {

            var localVarPath = "/stats/season";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (seriesId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "seriesId", seriesId)); // query parameter
            if (season != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "season", season)); // query parameter
            // authentication (Bearer) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StatsSeasonGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Collection<SeasonStat>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Collection<SeasonStat>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Collection<SeasonStat>)));
        }

    }
}
